### ISSUE TITLE
[EPIC] Support all TPC-H queries in benchmark

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#158]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11519

This is a tracking issue for supporting all of the TPC-H queries.

Supporting all of the queries will add a number of features and helps DataFusion become a robust & fast query engine.

- [x] q1
- [x] https://github.com/apache/arrow-datafusion/issues/159
- [x] q3
- [x] https://github.com/apache/arrow-datafusion/issues/160
- [x] q5
- [x] q6
- [x] q7
- [x] q8
- [x] q9
- [x] q10
- [x] https://github.com/apache/arrow-datafusion/issues/163
- [x] q12
- [x] q13
- [x] q14
- [x] https://github.com/apache/arrow-datafusion/issues/166
- [x] q16
- [x] https://github.com/apache/arrow-datafusion/issues/168
- [x] q18
- [x] q19
- [x] https://github.com/apache/arrow-datafusion/issues/171
- [x] https://github.com/apache/arrow-datafusion/issues/172
- [x] https://github.com/apache/arrow-datafusion/issues/175

**Comment by avantgardnerio** [comment]
I'm actively working on these, and I think my incoming PR will resolve all the ones with subqueries. I'm filing notes on the subtasks as I go.

**Comment by alamb** [comment]
Thank you @avantgardnerio

**Comment by andygrove** [comment]
I think this can be closed now!

**Comment by alamb** [comment]
Wow -- that almost is worth a blog post itself!

**Comment by Dandandan** [comment]
This is truly epic :tada: and a big milestone thanks for all involved!
