### ISSUE TITLE
[EPIC] Improve DataFusions ability to work with files

### ISSUE THREAD

**Issue by matthewmturner** [apache/arrow-datafusion#1777]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

I would like to add functionality for writing files from DataFusion.  To start, I've thought of the below.

- [ ] (1) Add write functionality to `ObjectStore`
- [x] (2)Add `write_json` to `ExecutionContext`
- [ ] (3) Add `write_arrow` to `ExecutionContext`
- [x] (4) Add `COPY` / `COPY TO` command for SQL (like postgres https://www.postgresql.org/docs/current/sql-copy.html)
- [ ] (5) Add ability to write partitioned datasets
- [ ] (6) Add support for writing metadata
- [x] (7) Add `write_csv` method to `DataFrame`
- [x] (8) Add `write_parquet` method to `DataFrame`
- [ ] (9) Add `write_arrow` method to `DataFrame`
- [x] (10) Add `write_json` method to `DataFrame`
- [x] (11) Add `read_json` method to `DataFrame`
- [x] (12) Add `read_json` method to `ExecutionContext`
- [x] (13) Add `register_json` method to `ExecutionContext`
- [x] (14) Support `IF NOT EXISTS` for `CREATE EXTERNAL TABLE`
- [ ] (15) Add `read_arrow` to `ExecutionContext`
- [ ] (16) Add `read_arrow` to `DataFrame`

I will use this as a parent / tracker issue for the above points which will each have an issue.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by matthewmturner** [comment]
Just wanted to create this to start collecting feedback / thoughts.  I havent had chance to really look into details of this yet.  I hope to start in a couple weeks when I have some more time.

**Comment by matthewmturner** [comment]
@seddonm1 @houqp FYI - in case you have any thoughts.

**Comment by matthewmturner** [comment]
@yjshen also interested in your view - in particular on the `ObjectStore` point.

**Comment by Igosuki** [comment]
@matthewmturner I'd love to see PARTITION BY be implemented, which would output typical k=v partitions usable by the ListingTableProvider.

**Comment by matthewmturner** [comment]
> @matthewmturner I'd love to see PARTITION BY be implemented, which would output typical k=v partitions usable by the ListingTableProvider.

@Igosuki  Agreed that would be great, I've added it to the list.

**Comment by Igosuki** [comment]
And, probably, support writing metadata, both arbitrary and specific to datafusion like other apache engines do ?

**Comment by xudong963** [comment]
The direct implementation of `COPY FROM` (copy data from a file to a table) is if a table exists, then we can create a new table from the file and `union` new table with the old table, otherwise, we can let the new table `union`s with an empty table with the same scheme. 

BTW, we should make `sqlparser-rs` support those commands firstly.

**Comment by matthewmturner** [comment]
> The direct implementation of `COPY FROM` (copy data from a file to a table) is if a table exists, then we can create a new table from the file and `union` new table with the old table, otherwise, we can let the new table `union`s with an empty table with the same scheme.
> 
> BTW, we should make `sqlparser-rs` support those commands firstly.

@xudong963 To confirm - does `COPY FROM` functionality already exist?  I'm not sure if i understood correctly, but I was focused on writing tables/dataframes from datafusion to files for this issue.

And definitely agree on checking `sqlparser-rs`. I will check that out.

**Comment by xudong963** [comment]
> To confirm - does `COPY FROM` functionality already exist

No, looking forward to seeing it. I just describe my idea of how to implement it.

**Comment by xudong963** [comment]
> And definitely agree on checking `sqlparser-rs`. I will check that out.

FYI @matthewmturner  https://github.com/sqlparser-rs/sqlparser-rs/pull/409/

**Comment by matthewmturner** [comment]
@xudong963 very helpful, thank you.

**Comment by matthewmturner** [comment]
@Igosuki Thx much.

Will keep you posted when I start working on this.

**Comment by matthewmturner** [comment]
From what I see it looks like only the execution context can write files right now - let me know if im mistaken.  I think it makes sense to add write functionality to dataframes as well.  I've added to the list.

**Comment by Igosuki** [comment]
@alamb is write_parquet outside of the scope now ?

**Comment by matthewmturner** [comment]
@alamb FYI I don't think this issue should be closed yet. I'm using it as a tracker with the task list in the description.

**Comment by matthewmturner** [comment]
@Igosuki just to confirm what youre looking for - you want to be able to write partitioned parquet files from SQL?

**Comment by Igosuki** [comment]
Exactly, like we can do with Spark.

Le dim. 6 mars 2022 à 16:55, Matthew Turner ***@***.***> a
écrit :

**Comment by alamb** [comment]
reopened -- I think github got a little over eager and interpreted the "closes #1777 task three" comment to mean it should close the tickt

![Screen Shot 2022-03-07 at 3 49 19 PM](https://user-images.githubusercontent.com/490673/157115585-d9c56d20-d7c9-435f-899a-28eb13399590.png)

**Comment by matthewmturner** [comment]
@Igosuki sry if im being dumb / bad at searching google but i havent been able to find an example / docs of writing partitioned parquet files from SQL. Only writing with dataframe API or reading a partitioned parquet dataset with SQL.  I havent had the chance to test, but is the command youre looking for something like:

```
COPY TABLE abc
TO `abc`
STORED AS PARQUET
PARTITION BY year, month
```

**Comment by Igosuki** [comment]
Personnally, I'm fine using the dataframe api, but the partitioned output isn't available right now in the API ? Spark goes with write.partitionBy(...).parquet("")

**Comment by matthewmturner** [comment]
Ok great - using dataframe api aligns more with my thinking. It was just the SQL part that was throwing me off. Thx.

**Comment by alamb** [comment]
We have pretty much completed the list on this ticket now. It is pretty amazing to see

https://docs.rs/datafusion/latest/datafusion/execution/context/struct.SessionContext.html#method.read_avro
https://docs.rs/datafusion/latest/datafusion/execution/context/struct.SessionContext.html#method.read_arrow
