### ISSUE TITLE
Support Multiple row layout

### ISSUE THREAD

**Issue by yjshen** [apache/arrow-datafusion#2188]
- [x] Move layout, null bits, and jit code to their separate module. Restructure code for clearness. #2189
- [x] Support 8-byte aligned layout for hash-buffer  #2261
- [x] Move row to its crate to enable usage from AggregateExpr. #2283 
- [ ] Research on inline varlena fields for raw-bytes-based comparison.
