### ISSUE TITLE
[EPIC] Subquery support

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2248]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We have many issues now for subquery support, with some duplication so I thought it would be good to create one epic to track all of this work.

There is also a [design document](https://docs.google.com/document/d/1j5vHyva-T_5l3POnHSS0-r5TOp86sEkfSUcRLqJZaK4/edit?usp=sharing).

## Logical Plan

- [x] https://github.com/apache/arrow-datafusion/issues/2247
- [x] https://github.com/apache/arrow-datafusion/issues/2245
- [x]  https://github.com/apache/arrow-datafusion/issues/2181
- [x] https://github.com/apache/arrow-datafusion/issues/2337
- [x] https://github.com/apache/arrow-datafusion/pull/2342

## SQL Query Planner

- [x] https://github.com/apache/arrow-datafusion/issues/2238
- [x] https://github.com/apache/arrow-datafusion/issues/2219
- [x] https://github.com/apache/arrow-datafusion/issues/2237
- [x] https://github.com/apache/arrow-datafusion/issues/2353

## Logical Plan Optimizations

- [ ] https://github.com/apache/arrow-datafusion/issues/2361
- [x] https://github.com/apache/arrow-datafusion/issues/2351
- [x] https://github.com/apache/arrow-datafusion/issues/488

## Physical Plan

- [ ] https://github.com/apache/arrow-datafusion/issues/1835
- [ ] https://github.com/apache/arrow-datafusion/issues/123

## Ballista

- [x] https://github.com/apache/arrow-datafusion/issues/2338

**Comment by jon-chuang** [comment]
Some additional ideas for subquery optimizations:
- If rest of subquery is not correlated, push up correlated filter (in particular, correlated equality filter) into a left join on the filter.
- More here: https://www.alibabacloud.com/blog/query-optimization-technology-for-correlated-subqueries_597644

**Comment by jon-chuang** [comment]
- [ ] https://github.com/apache/arrow-datafusion/issues/2480

**Comment by alamb** [comment]
I filed https://github.com/apache/arrow-datafusion/issues/5483 to track the few items that are not done yet, and am going to close this ticket as we have subquery support in DataFusion now 🎉
