### ISSUE TITLE
[Epic] Type-coercion improvements

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2355]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I am running into type-coercion errors and am probably going to be adding more hacks to the existing implementation but would like to start tracking the work we need to do to improve the type-coercion logic as well as the various open issues that are related to type-coercion.

Examples of issues:

- [x] https://github.com/apache/arrow-datafusion/issues/2420
- [x] https://github.com/apache/arrow-datafusion/issues/1335
- [x] https://github.com/apache/arrow-datafusion/issues/1193
- [x] https://github.com/apache/arrow-datafusion/issues/1192
- [x] https://github.com/apache/arrow-datafusion/issues/1188
- [x] https://github.com/apache/arrow-datafusion/issues/1179
- [x] https://github.com/apache/arrow-datafusion/issues/201
- [x] https://github.com/apache/arrow-datafusion/issues/185
- [x] https://github.com/apache/arrow-datafusion/issues/81
- [x] https://github.com/apache/arrow-datafusion/issues/2447
- [x] https://github.com/apache/arrow-datafusion/issues/3221
- [x] https://github.com/apache/arrow-datafusion/pull/3254
- [x] https://github.com/apache/arrow-datafusion/issues/3388
- [x] https://github.com/apache/arrow-datafusion/issues/3390
- [ ] https://github.com/apache/arrow-datafusion/issues/3419
- [x] https://github.com/apache/arrow-datafusion/issues/3431

**Comment by Dandandan** [comment]
I added https://github.com/apache/arrow-datafusion/issues/3431 to the list.

**Comment by alamb** [comment]
The list is complete!
