### ISSUE TITLE
[EPIC] A collection of Date/Time related open issues

### ISSUE THREAD

**Issue by waitingkuo** [apache/arrow-datafusion#3148]
This is followed on the Proposal for Date/Time enhancement  #3100
Please edit the list or comment bellow if you find something not listed here.

## Date/Time/Timestamp Types & Casting

- [x] #2883 - This is the initial work for `TIME` literal (i.e. make `SELECT TIME '00:00:00';` work)
- [x] apache/arrow-rs#2074 - This is to improve the performance of casting timestamp between different unit
- [x] #193 - This depends on #2883
- [x] #3082 
- [ ] https://github.com/apache/arrow-datafusion/issues/5398
- [ ] https://github.com/apache/arrow-datafusion/issues/7868
- [x] https://github.com/apache/arrow-datafusion/issues/6653
- [x] https://github.com/apache/arrow-datafusion/issues/6701
- [x] https://github.com/apache/arrow-datafusion/issues/6720

## TimestampTz Date Types & Casting & Coercion

- [x] apache/arrow-rs#597
- [x] apache/arrow-rs#599
- [x] apache/arrow-rs#168
- [x] #153
- [ ] #3080 
- [ ] #959 
- [x] #3149 
- [x] sqlparser-rs/sqlparser-rs#588
- [x] sqlparser-rs/sqlparser-rs#464
- [x] #3659 
- [x] apache/arrow-rs#2813
- [x] #3693 
- [x] #3715
- [x] apache/arrow-rs#2909
- [x] apache/arrow-rs#2910
- [x] apache/arrow-rs#1936
- [x] #4311 
- [x] https://github.com/apache/arrow-datafusion/issues/4853
- [x] https://github.com/apache/arrow-datafusion/issues/5164
- [x] https://github.com/apache/arrow-datafusion/issues/5507
- [x] https://github.com/apache/arrow-datafusion/issues/7070
- [x] https://github.com/apache/arrow-datafusion/issues/7697

## Intervals
See https://github.com/apache/arrow-datafusion/issues/5753

## Arithmetic (including intervals)

- [x] #200
- [x] #194
- [x] #3103 
- [x] https://github.com/apache/arrow-datafusion/issues/5413
- [x] apache/arrow-rs#593
- [x] apache/arrow-rs#527
- [x] apache/arrow-rs#187
- [x] apache/arrow-rs#2457 - arrow-rs
- [x] #3157 - datafusion
- [x] #3166 
- [x] #3180
- [x] apache/arrow-rs#1065
- [x] #3204
- [x] #4420
- [x] #4644 
- [x] #5411 
- [x] #5650
- [x] #5704 
- [ ] #6951
- [x] https://github.com/apache/arrow-datafusion/issues/7068
- [ ] https://github.com/apache/arrow-datafusion/issues/8275

## Functions

- [x] #3096 
- [x] #3057 
- [x] #2979
- [ ] #1992
- [x] #765
- [ ] #686
- [x] apache/arrow-rs#1380 
- [x] #765
- [x] #3832 
- [x] apache/arrow-rs#2892
- [x] #3980
- [x] #3981
- [x] #3982
- [ ] #3996
- [x] #3997 
- [x] sqlparser-rs/sqlparser-rs#748
- [x] #4528
- [x] #2785
- [x] https://github.com/apache/arrow-datafusion/issues/5641
- [ ] #5568 
- [ ] https://github.com/apache/arrow-datafusion/issues/6876
- [x] https://github.com/apache/arrow-datafusion/issues/7604

## parquet/csv/json

- [x] apache/arrow-rs#982
- [x] apache/arrow-rs#1191
- [x] apache/arrow-rs#1060
- [x] apache/arrow-rs#455
- [x] apache/arrow-rs#38
- [x] #2044
- [x] #3176 

## others 

- [ ] apache/arrow-rs#902
- [x] #3255
- [x] sqlparser-rs/sqlparser-rs#303
- [x] #4104

**Comment by alamb** [comment]
This is amazing @waitingkuo  -- thank you

**Comment by liukun4515** [comment]
@waitingkuo you can @ me to review your pr about the times.
I care about this part

**Comment by avantgardnerio** [comment]
Proposal:

We attack this in multiple steps parts:
1. Add `timestamp` but not `timestamp with timezone`
2. Hard code the server "local" time zone to always be UTC, such that `show time zone` always returns UTC and `set time zone 'UTC'` is the only `set` command that will not produce an error
3. Add `timestamp with timezone`, but it will always be UTC due to the above
4. Add support for `set time zone 'UTC+8'`
5. Add support for `set timezone 'US/Mountain`

I think the above plan will allow us to tackle the problem in stages, without ever technically breaking ANSI compliance and reaching full compliance at the end state. Caveat: I'm not sure if we will ever reach the end state, and I'm okay with that personally.

**Comment by alamb** [comment]
Thank you @avantgardnerio and @waitingkuo  for driving this issue. It is awesome to see

**Comment by waitingkuo** [comment]
@alamb  @avantgardnerio i just finished 

1. Add timestamp but not timestamp with timezone
2. Hard code the server "local" time zone to always be UTC, such that show time zone always returns UTC and set time zone 'UTC' is the only set command that will not produce an error

i'm just starting the work for `timestamp with timezone`, things become trickier now 

postgresql has this 
<https://www.postgresql.org/docs/current/functions-formatting.html>
```
to_timestamp ( text, text ) → timestamp with time zone
```
Converts string to time stamp according to the given format. (See also to_timestamp(double precision) in [Table 9.32](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TABLE).)

to_timestamp('05 Dec 2000', 'DD Mon YYYY') → 2000-12-05 00:00:00-05


and this 
<https://www.postgresql.org/docs/current/functions-datetime.html>
```
to_timestamp ( double precision ) → timestamp with time zone
```
Convert Unix epoch (seconds since 1970-01-01 00:00:00+00) to timestamp with time zone
to_timestamp(1284352323) → 2010-09-13 04:32:03+00

Looks like its `to_timestamp` always return `timestamp with time zone`

Do you think we should align these function signatures with postgresql?
There will be more things to change once we have timestamp with non-UTC timezone 💔 

BTW
Datafusion's `now()` output `timestamp with time zone` which is same as what postgresql has 👍

**Comment by alamb** [comment]
> In general, do you think we should align these function signatures with postgresql?
> There will be more things to change once we have timestamp with non-UTC timezone 💔

I think it would be ok to align the functions with postgres as long as there is some clear way to get the current behavior as well (e.g. the query needs to be tweaked or something)

**Comment by alamb** [comment]
I filed https://github.com/apache/arrow-datafusion/issues/3980 and added it to this ticket -- I plan to add more date/time open issues here to help track them

**Comment by mjvankampen** [comment]
I think #2785 belongs in this list as well!

**Comment by waitingkuo** [comment]
added, thank you @mjvankampen

**Comment by alamb** [comment]
Filed See https://github.com/apache/arrow-datafusion/issues/5753 to track work for intervals

**Comment by watfordkcf** [comment]
We're ramping up our usage of delta-rs (and with it arrow-datafusion) and would like to see resolved much of the weirdness with dates/times (ignoring the absolute pain Spark brings upstream). Don't want to duplicate effort, so would help with #959 (and #6876) be welcomed?

**Comment by alamb** [comment]
Hi @watfordkcf -- thanks!

I believe @tustvold  is in the middle of cleaning and making consistent the various timestamp arithmetic / kernels / intervals

The largest outstanding gap that I know of is correct timezone handling (basically anything other than UTC timestamps are like to hit corner cases / bugs) -- this is related to https://github.com/apache/arrow-datafusion/issues/959


In terms of https://github.com/apache/arrow-datafusion/issues/6876, that would be lovely I think.

**Comment by liukun4515** [comment]
Do we have any method to convert or cast the integer type/integer expr with the timeunit to the interval?

@waitingkuo  @alamb

**Comment by alamb** [comment]
@liukun4515  there is the `interval` constant syntax:

```
DataFusion CLI v27.0.0
❯ select interval '5 days';
+-------------------------------------------------------+
| IntervalMonthDayNano("92233720368547758080")          |
+-------------------------------------------------------+
| 0 years 0 mons 5 days 0 hours 0 mins 0.000000000 secs |
+-------------------------------------------------------+
1 row in set. Query took 0.025 seconds.
```

Also casting strings to intervals handle units

```

❯ select '5 days'::interval;
+-------------------------------------------------------+
| Utf8("5 days")                                        |
+-------------------------------------------------------+
| 0 years 0 mons 5 days 0 hours 0 mins 0.000000000 secs |
+-------------------------------------------------------+
1 row in set. Query took 0.003 seconds.
```

Or creating a string via `||`
```
❯ select (5 || ' days')::interval;
+-------------------------------------------------------+
| Int64(5) || Utf8(" days")                             |
+-------------------------------------------------------+
| 0 years 0 mons 5 days 0 hours 0 mins 0.000000000 secs |
+-------------------------------------------------------+
1 row in set. Query took 0.004 seconds.

**Comment by liukun4515** [comment]
> @liukun4515 there is the `interval` constant syntax:
> 
> ```
> DataFusion CLI v27.0.0
> ❯ select interval '5 days';
> +-------------------------------------------------------+
> | IntervalMonthDayNano("92233720368547758080")          |
> +-------------------------------------------------------+
> | 0 years 0 mons 5 days 0 hours 0 mins 0.000000000 secs |
> +-------------------------------------------------------+
> 1 row in set. Query took 0.025 seconds.
> ```
> 
> Also casting strings to intervals handle units
> 
> ```
> 
> ❯ select '5 days'::interval;
> +-------------------------------------------------------+
> | Utf8("5 days")                                        |
> +-------------------------------------------------------+
> | 0 years 0 mons 5 days 0 hours 0 mins 0.000000000 secs |
> +-------------------------------------------------------+
> 1 row in set. Query took 0.003 seconds.
> ```
> 
> Or creating a string via `||` (which is the same as the concat you mention above)
> 
> ```
> ❯ select (5 || ' days')::interval;
> +-------------------------------------------------------+
> | Int64(5) || Utf8(" days")                             |
> +-------------------------------------------------------+
> | 0 years 0 mons 5 days 0 hours 0 mins 0.000000000 secs |
> +-------------------------------------------------------+
> 1 row in set. Query took 0.004 seconds.
> ```

` 5|| ' DAY'` is same with concat( 5, ' day') ?

I use this method concat to complete my requirements, but the performance may be not better.

https://github.com/apache/arrow-datafusion/issues/6876#issuecomment-1631086729 also provide the thoughts about support the `make_interval` function

cc @watfordkcf

**Comment by waitingkuo** [comment]
@liukun4515 
added, thank you

**Comment by alamb** [comment]
Wow the list of tickets fixed is quite impressive: ![image](https://github.com/apache/arrow-datafusion/assets/490673/6004cde9-350b-4ae8-bc36-29ff4e87f128)
