### ISSUE TITLE
[Epic] Support for unsigned integer types

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#3376]
This is a tracking epic to properly support Unsigned Integer Types.

DataFusion has fairly robust support for signed types like `Int32`, `Int64`, etc. https://github.com/apache/arrow-datafusion/pull/3359 added the ability to refer to unsigned types like `UNSIGNED INT` in SQL

The primary rationale for supporting unsigned integers is testing and better integration with the Arrow ecosystem (not, for example, performance). See additional discussion on supporting unsigned types here; https://github.com/apache/arrow-datafusion/issues/3325

Here are a list of items we still know of to complete
- [x] https://github.com/apache/arrow-datafusion/issues/3307
- [x] https://github.com/apache/arrow-datafusion/issues/3325
- [ ] physical operation (e.g. binary.rs)
- [ ] type coercion
- [x] https://github.com/apache/arrow-datafusion/issues/5475
- [x] https://github.com/apache/arrow-datafusion/issues/81
- [x] https://github.com/apache/arrow-datafusion/issues/5475

**Comment by alamb** [comment]
I think this is done and unsigned ints work pretty well now:

```
DataFusion CLI v34.0.0
❯ create table foo (x int unsigned);
0 rows in set. Query took 0.002 seconds.

❯ insert into foo values (1);
+-------+
| count |
+-------+
| 1     |
+-------+
1 row in set. Query took 0.002 seconds.

❯ select arrow_typeof(x) from foo;
+---------------------+
| arrow_typeof(foo.x) |
+---------------------+
| UInt32              |
+---------------------+
1 row in set. Query took 0.002 seconds.

❯ select x + 4 from foo;
+------------------+
| foo.x + Int64(4) |
+------------------+
| 5                |
+------------------+
1 row in set. Query took 0.004 seconds.
```
