### ISSUE TITLE
[META] Improving cost calculations and cost based optimizations

### ISSUE THREAD

**Issue by isidentical** [apache/arrow-datafusion#3929]
This is a meta issue for improving cost calculations and cost-based optimizations in DataFusion. We already have some statistics collected (mainly from the table sources) and there are estimations for statistics by some of the execution plan nodes, and the overall idea is to improve these as well as possible CBOs.

### Main Goals
- Have enough statistics to start nested join optimizations (#3843). This involves being able to guess the weight of a join side, and do global re-ordering between join sides to minimize the overall cost of parent joins by reducing the output as much as possible at the bottom levels.
- Provide a more reliable static analysis phase for physical execution operators (so that range based pruning/predicate pruning can leverage the existing infrastructure on their implementations)
- What else?

### Work in Progress

- [ ] https://github.com/apache/arrow-datafusion/issues/3898
- [ ] https://github.com/apache/arrow-datafusion/issues/3845
- What else?

### Planned
- [ ] Estimating join cardinalities when the underlying table does not have any statistics (https://github.com/apache/arrow-datafusion/issues/3813#issuecomment-1276643214).
- What else?

**Comment by isidentical** [comment]
@alamb @Dandandan @mingmwang I've created the meta/epic issue as we discussed

**Comment by alamb** [comment]
I believe the next step is some sort of design document.

**Comment by Dandandan** [comment]
Maybe you can share the doc publicly so anyone can do suggestions?

**Comment by alamb** [comment]
I plan to review the doc carefully tomorrow ❤️

**Comment by isidentical** [comment]
Thanks @alamb! I'll also try to talk a bit more about it with real-world examples in the [tomorrow's meeting](https://arrow.apache.org/datafusion/contributor-guide/communication.html#sync-up-video-calls) from scratch (if we would have the time for that in this meetup, and if I can actually make it there), just in case if anyone is also planning to attend.

**Comment by alamb** [comment]
I filed a ticket to discuss a potentially more general approach to join ordering and access path selection
- https://github.com/apache/datafusion/issues/17718
