### ISSUE TITLE
[Epic] Data Driven Tests

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#4460]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
As described in https://github.com/apache/arrow-datafusion/issues/4248 and implemented in https://github.com/apache/arrow-datafusion/pull/4395 we now have a sqlogictest based test framework in DataFusion 🎉 

This ticket tracks the various follow on work we would like to do

**Describe the solution you'd like**

Basically we would like to follow the DuckDB variant of sqllogictest as much as possible: https://duckdb.org/dev/sqllogictest/intro

The current rules for verification can be found in: https://duckdb.org/dev/sqllogictest/result_verification

**Items**
- [x] https://github.com/apache/arrow-datafusion/issues/4248
- [x] https://github.com/apache/arrow-datafusion/pull/4395
- [x] https://github.com/apache/arrow-datafusion/issues/4471
- [x] https://github.com/apache/arrow-datafusion/issues/4396
- [x] https://github.com/apache/arrow-datafusion/issues/4397
- [x] #4499
- [x] #4500
- [x] #4498
- [x] https://github.com/apache/arrow-datafusion/issues/4462
- [x] https://github.com/apache/arrow-datafusion/issues/4494
- [x] https://github.com/apache/arrow-datafusion/issues/4495
- [ ] Port existing sqllogictests from other systems to DataFusion
- [ ] https://github.com/apache/arrow-datafusion/issues/6195
- [x] https://github.com/apache/arrow-datafusion/issues/4502
- [x] https://github.com/apache/arrow-rs/issues/3268
- [x] https://github.com/apache/arrow-datafusion/pull/4497
- [x] https://github.com/apache/arrow-datafusion/pull/4504
- [x] #4570
- [x] https://github.com/apache/arrow-datafusion/issues/4709
- [x] https://github.com/apache/arrow-datafusion/issues/4734
- [ ] https://github.com/apache/arrow-datafusion/issues/4769
- [x] https://github.com/apache/arrow-datafusion/issues/4870
- [x] https://github.com/apache/arrow-datafusion/issues/5009
- [x] https://github.com/apache/arrow-datafusion/issues/5010
- [x] https://github.com/apache/arrow-datafusion/issues/5011
- [x] https://github.com/apache/arrow-datafusion/issues/5016
- [x] https://github.com/apache/arrow-datafusion/issues/6392
- [x] https://github.com/apache/arrow-datafusion/issues/6405

**Describe alternatives you've considered**

**Additional context**
cc @mvanschellebeeck @xudong963

**Comment by xudong963** [comment]
I'll add more TODOs tomorrow.

**Comment by alamb** [comment]
@xudong963  I think a fun project might be to figure out how to support a minimal implementation of INSERT to insert data. Maybe by implementing something entirely in the sqllogictest harness using ArrayBuilders 🤔  It doesn't have to handle errors well initially or be performant.

I wonder if something crazy like forming a single row record batch from the input, and then `concat` that batch with any existing batches would be good enough 🤔

**Comment by xudong963** [comment]
@alamb Today I have a more crazy idea: we can use **Postgres** to run `create table` and `insert into ...` for DF.

To implement the idea, we can register two DBs for sqllogictest runner, PG and DF.

For pg: we can register Postgres client in our logictest by use `tokio_postgres::Client` and start Postgres server in docker.

Here is a draft PR to verify if my idea is feasible in sqllogictest-rs: https://github.com/xudong963/sqllogictest-rs/pull/1

**Comment by alamb** [comment]
🤔  I wonder @xudong963  how will inserting data into postgres allow us to insert data into DataFusion 🤔

**Comment by alamb** [comment]
Also, heads up I have some ideas on how to improve the sqllogic framework https://github.com/apache/arrow-datafusion/pull/4492#issuecomment-1336162634

**Comment by xudong963** [comment]
> 🤔 I wonder @xudong963 how will inserting data into postgres allow us to insert data into DataFusion 🤔

Seems it's impossible, my mistake.

**Comment by xudong963** [comment]
> I wonder if something crazy like forming a single row record batch from the input, and then `concat` that batch with any existing batches would be good enough 🤔

Make sense to me.

**Comment by mvanschellebeeck** [comment]
hey @alamb could you also add https://github.com/apache/arrow-datafusion/issues/4495 and https://github.com/apache/arrow-datafusion/issues/4494 as issues under the epic?

**Comment by xudong963** [comment]
> hey @alamb could you also add #4495 and #4494 as issues under the epic?

added

**Comment by alamb** [comment]
Update: check out the insert proposal from @xudong963  here https://github.com/apache/arrow-datafusion/pull/4496 🥳 🦜

**Comment by mvanschellebeeck** [comment]
@xudong963 / @alamb - could we also add https://github.com/apache/arrow-datafusion/issues/4502

**Comment by alamb** [comment]
> @alamb Please help to add https://github.com/apache/arrow-datafusion/issues/6405 and assign it to me.

Done @liurenjie1024 -- thank you

**Comment by alamb** [comment]
I think I am going to claim this epic is substantially done so I am closing it out (we have pretty good data driven testing now) The rest of the stragglers I think are tracked in their own tickets without issue
