### ISSUE TITLE
[EPIC] More Subquery support

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#5483]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

DataFusion supports many types of subqueries (originally tracked via https://github.com/apache/arrow-datafusion/issues/2248). This epic tracks additional features / support

See also the original  [design document](https://docs.google.com/document/d/1j5vHyva-T_5l3POnHSS0-r5TOp86sEkfSUcRLqJZaK4/edit?usp=sharing).

## Physical Plan

- [ ] https://github.com/apache/arrow-datafusion/issues/1835
- [ ] https://github.com/apache/arrow-datafusion/issues/123
- [ ] https://github.com/apache/arrow-datafusion/issues/2480

**Comment by Y-jiji** [comment]
I want to try this for GSoC. Leave an email: tyang425@gatech.edu

**Comment by yashdavkhar7020** [comment]
🚀 Interested in Contributing to Correlated Subqueries in DataFusion

Hi 

I am Yash Davkhar, and I am highly interested in contributing to this project on adding support for correlated subqueries in DataFusion. I have experience in SQL, database systems, and query optimization and would love to apply my skills to improve DataFusion’s SQL engine.

I have gone through the project description and the linked epic, and I would appreciate any guidance on how to get started. Could you please share any specific tasks or areas I should focus on first?

Looking forward to contributing! 🚀

Best regards,
Yash Davkhar

**Comment by SanjayUG** [comment]
Hi there,

Looks interesting issue, I would love to contribute to it without any fiction.

Thank You.

**Comment by PhaniKulkarni** [comment]
Hi, I am interested in contributing to Apache DataFusion, specifically in implementing correlated subqueries support

I have experience in SQL Engines, Data Migration and query optimization and have gone through DataFusion’s documentation and source code. However, I would appreciate some guidance on:

1. Where to start in understanding DataFusion’s query planning and optimization workflow.

2. Any specific resources or previous discussions that would be helpful.

3. How best to break down the implementation steps before submitting a PR.

A brief discussion would be greatly appreciated.

Here is my contact and profile details:
LinkedIn: https://www.linkedin.com/in/phani-kulkarni-140674180/
Mail: kulkarniphani@gmail.com

Thanks and Regards,
Phani Kulkarni

**Comment by alamb** [comment]
- I am trying to organize a join task force for planning joins / subqueries: https://github.com/apache/datafusion/issues/15885

**Comment by adriangb** [comment]
Dropping an example that I was surprised didn't work, I think related to this:

```sql
> CREATE TABLE t(col text) AS VALUES ('foo');
0 row(s) fetched. 
Elapsed 0.005 seconds.

> SELECT EXISTS (
    SELECT 1 
    FROM t 
    WHERE col = 'value'
) AS exst;
This feature is not implemented: Physical plan does not support logical expression Exists(Exists { subquery: <subquery>, negated: false })
```
