### ISSUE TITLE
[EPIC] Schema mismatches with batches schema

### ISSUE THREAD

**Issue by comphead** [apache/arrow-datafusion#5747]
### Describe the bug

This is un umbrella to cover different bugs with internal schema during query execution leading to 
`Error during planning: Mismatch between schema and batches`

- [x] Windowing query shortened the alias -> workaround provide alias https://github.com/apache/arrow-datafusion/issues/5695#issuecomment-1481413999
- [x]  Union all query incorrectly derive column aliases https://github.com/apache/arrow-datafusion/issues/5695#issuecomment-1482086910
- [x] Inconsistent column naming https://github.com/apache/arrow-datafusion/issues/5695#issuecomment-1483550835
- [x] Case statement with one branch being null #5733 
- [x] LEFT Join https://github.com/apache/arrow-datafusion/issues/5695#issuecomment-1483877234 -> https://github.com/apache/arrow-datafusion/pull/5748
- [x] RIGHT/FULL Join https://github.com/apache/arrow-datafusion/pull/6015
### To Reproduce

Reproduce steps are in the tickets

### Expected behavior

Fix bugs

### Additional context

Initially came from https://github.com/apache/arrow-datafusion/issues/5695

**Comment by comphead** [comment]
@alamb please assign this to me

**Comment by comphead** [comment]
@mslapek @jackwener @milevin CC as likely working on similar fix https://github.com/apache/arrow-datafusion/issues/5681

**Comment by alamb** [comment]
🎉
