### ISSUE TITLE
[EPIC] More complete support for `INTERVAL` 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#5753]
This ticket tracks work to properly support the `Interval` type

- [x] https://github.com/apache/arrow-datafusion/issues/194
- [x] https://github.com/apache/arrow-datafusion/issues/5651
- [x] https://github.com/apache/arrow-datafusion/issues/5652
- [x] https://github.com/apache/arrow-datafusion/issues/5689
- [x] https://github.com/apache/arrow-datafusion/issues/5704
- [x] https://github.com/apache/arrow-rs/issues/3958
- [x] #5801
- [x] https://github.com/apache/arrow-datafusion/issues/5802
- [x] https://github.com/apache/arrow-datafusion/issues/6180
- [x] https://github.com/apache/arrow-datafusion/issues/6205
- [x] https://github.com/apache/arrow-datafusion/issues/6155
- [x] https://github.com/apache/arrow-rs/issues/3999
- [x] https://github.com/apache/arrow-rs/issues/4383
- [ ] https://github.com/apache/arrow-datafusion/issues/6720

**Comment by alamb** [comment]
I captured upstream extensions to arrow-rs in https://github.com/apache/arrow-rs/issues/3958

**Comment by alamb** [comment]
I think this is basically done, so closing it down. I think https://github.com/apache/arrow-datafusion/issues/6720 doens't need an epic to track it
