### ISSUE TITLE
Complete Implement fast Vectorized grouping for high cardinality

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#6889]
### Is your feature request related to a problem or challenge?

This is a summary issue tracking the work to complete the design described in https://github.com/apache/arrow-datafusion/issues/4973#issuecomment-1608068287

### Describe the solution you'd like

- [x] Create a POC demonstrating sufficient improvement: https://github.com/apache/arrow-datafusion/pull/6800
- [x] Create a PR to use the new GroupsAggregators: https://github.com/apache/arrow-datafusion/pull/6904 
- [x] https://github.com/apache/arrow-datafusion/issues/6955
- [x] File ticket for Optimize inner loop / null calculation performance https://github.com/apache/arrow-datafusion/issues/7066
- [x] Add tests for min/max aggregates on Strings: https://github.com/apache/arrow-datafusion/pull/6962
- [x] https://github.com/apache/arrow-datafusion/issues/6798
- [x] Remove RowAggregators and the now unused row format https://github.com/apache/arrow-datafusion/pull/6968
- [ ] #6988
- [x] File a ticket for avoiding reallocations in accumulators (suggested y @yjshen  on https://github.com/apache/arrow-datafusion/pull/6800#discussion_r1251142165): https://github.com/apache/arrow-datafusion/issues/7065
- [x] File a ticket for fast min/max accumulator for strings : https://github.com/apache/arrow-datafusion/issues/6906
- [x] File a ticket about special casing single column group by queries and avoiding the row conversion (suggested by @Dandandan  on https://github.com/apache/arrow-datafusion/pull/6800#issuecomment-1627472688): https://github.com/apache/arrow-datafusion/issues/6969

**Comment by alamb** [comment]
I am claiming success this ticket 🎉  -- I have the blog post https://github.com/apache/arrow-datafusion/issues/6988 written, and will get a PR up with a proposal in a few days, but I see no value in keeping this ticket open longer, so I am closing it

Thanks everyone for their help!
