### ISSUE TITLE
Consolidate datafusion benchmarks into dfbench

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7052]
### Is your feature request related to a problem or challenge?

DataFusion currently has four different benchmark runners for comparing different versions of datafusion with itself, which have substantial overlap in their functionality and code

```
cargo run --release --bin nyctaxi
cargo run --release --bin h2o
cargo run --release --bin parquet
cargo run --release --bin tpch
```

I would like to add a 5th one (ClickBench) https://github.com/apache/arrow-datafusion/issues/6994 but would like to avoid copy/pasting yet again mostly the same thing

### Describe the solution you'd like

Thus I propose a new consoidated binary `dfbench` run like this:

```
cargo run --release --bin benchmark -- nyctaxi
cargo run --release --bin benchmark -- h2o
cargo run --release --bin benchmark -- parquet
cargo run --release --bin benchmark -- tpch
cargo run --release --bin benchmark -- clickbench (I want to add this)
```

### Describe alternatives you've considered

Follow the same pattern

### Task List

- [x] Make consolidated runner `dfbench`: https://github.com/apache/arrow-datafusion/pull/7054
- [x] consolidate tpch: https://github.com/apache/arrow-datafusion/pull/7054
- [x] Update the benchmark readme
- [x] consolidate nyctaxi
- [ ] consolidate h2o -- tracked by https://github.com/apache/arrow-datafusion/issues/7209
- [x] consolidate parquet
- [x] Update bench.sh for new commands
- [x] Move tpch queries into `queries/tpch` rather than `queries`

**Comment by alamb** [comment]
I have completed all the work I have planned for this epic -- consolidating h20.ai bench is tracked by https://github.com/apache/arrow-datafusion/issues/7209 so I am going to close this one as complete
