### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Nov 6, 2023

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8063]
The idea of this ticket is to log plans I have each week for DataFusion related items.

This is largely for my own personal organizational needs and I think it will help me remain better focused, but I also figured it might serve as an interesting summary of what is happening in DataFusion this week

Major items I know for this week:
- [ ] Several more editing passes for the SIGMOD paper: https://github.com/apache/arrow-datafusion/issues/6782 with @ozankabak @Dandandan @yjshen and @JayjeetAtGithub 
- [ ] Write up some idea of "growing and sustaining the DataFusion community" that I have discussed with @andygrove @thinkharderdev @sunchao @viirya  and others
- [x] Assist with cleaning up array functions, and getting good patterns going: https://github.com/apache/arrow-datafusion/pull/8054 with @jayzhan211  (e.g. https://github.com/apache/arrow-datafusion/pull/8054)
- [ ] Unify BuiltInScalarFunctions with ScalarUDF: https://github.com/apache/arrow-datafusion/issues/8045, get agreement and get first few PRs ready with @2010YOUY01 
- [ ] Assist with sort based optimization work started in https://github.com/apache/arrow-datafusion/pull/8006 (encapsulating more structs, e.g https://github.com/apache/arrow-datafusion/pull/8034 and reviews) with @ozankabak  and @mustafasrepo 
- [ ] Review any new ticket / bug reports

**Comment by 2010YOUY01** [comment]
This is a good idea, maybe we can also list some tasks that have been identified as valuable but do not yet have someone working on them.

**Comment by alamb** [comment]
I updated the "unify function implementation plan" with @2010YOUY01  -- https://github.com/apache/arrow-datafusion/issues/8045 and made an initial PR to make `ScalarUDF` fields non pub: https://github.com/apache/arrow-datafusion/pull/8079

**Comment by alamb** [comment]
It turns out that https://github.com/apache/arrow-datafusion/issues/8078 is important for an internal project in IOx, so I plan to work on that as well

**Comment by alamb** [comment]
Next week's plan: https://github.com/apache/arrow-datafusion/issues/8151
