### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Nov 13, 2023

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8151]
The idea of this ticket is to log plans I have each week for DataFusion related items, largely for my own personal organizational needs, but also trying to
1. Try some different ways to communicate / coordinate int he community
2. Help provide an interesting summary of what is happening in DataFusion this week

It would be awesome if anyone else who has definite DataFusion plans could try something like this (maybe tickets are the best place 🤔 )

Major items I plan for personally this week:
- [x] Final week of "major" edits to SIGMOD paper (I plan to revise / improve diagrams and some wordig): https://github.com/apache/arrow-datafusion/issues/6782 with @ozankabak @Dandandan @yjshen and @JayjeetAtGithub  @sunchao and @viirya
- [ ] Write up ideas of "growing and sustaining the DataFusion community" 
- [ ] Improve representation of statistics to support better optimizatons: https://github.com/apache/arrow-datafusion/issues/8078

Projects I am watching / trying to help review and coordinate if needed
- [ ] Memory explosion in HashJoin outputs: https://github.com/apache/arrow-datafusion/issues/7848 with @korowa 
- [x] Disconnecting ListingTable (object store) from streaming usecase, add `StreamingTable` like API  https://github.com/apache/arrow-datafusion/issues/7994 with @metegenez and @ozankabak 
- [ ] `ARRAY` function hardening:  https://github.com/apache/arrow-datafusion/issues/6980 / https://github.com/apache/arrow-datafusion/issues/7988with @jayzhan211 @Veeupup @edmondop and @xudong963  (e.g. https://github.com/apache/arrow-datafusion/pull/8054)
- [ ] Make function packages more modular (make all BuiltInScalarFunctions ScalarUDFs): https://github.com/apache/arrow-datafusion/issues/8045 with @2010YOUY01 (get initial PR merged, help @2010YOUY01 lay the foundation, prepare first function extractions)
- [ ] Sort based optimization work started in https://github.com/apache/arrow-datafusion/pull/8006 (encapsulating more structs, e.g https://github.com/apache/arrow-datafusion/pull/8034 and reviews) with @ozankabak  and @mustafasrepo 
- [ ] Review any new ticket / bug reports

**Comment by alamb** [comment]
Also, help user defined types / LogicalType intoduction with @yukkit : https://github.com/apache/arrow-datafusion/pull/8143

**Comment by alamb** [comment]
Wrote up https://github.com/apache/arrow-datafusion/discussions/8152# as part of communty growth

**Comment by edmondop** [comment]
I was considering this issue https://github.com/apache/arrow-datafusion/issues/7955 @alamb do you think it's something that makes sense given your plan?

**Comment by alamb** [comment]
> I was considering this issue #7955 @alamb do you think it's something that makes sense given your plan?

I think this is a complicated feature and unfortunately don't have time at the moment to help it through the process. Perhaps other contributors such as @Dandandan  or @sunchao  / @viirya  would have time to help shepherd / work with you on the implementation.

**Comment by edmondop** [comment]
any simpler, more immediate issues in mind? I tried to search issues tagged with good-first-issue label but many of them had "some history" so maybe there are some of them that come to your mind that are higher priority/more useful

https://github.com/apache/arrow-datafusion/issues?page=2&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22

**Comment by alamb** [comment]
> any simpler, more immediate issues in mind? I tried to search issues tagged with good-first-issue label but many of them had "some history" so maybe there are some of them that come to your mind that are higher priority/more useful
> 
> https://github.com/apache/arrow-datafusion/issues?page=2&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22

Thanks for asking @edmondop  -- I don't know of any that are great candidates at this time (It takes a non trivial amount of time to write them up, and then they get done very quickly :)) -- I will try and write up some more shortly.

I filed some more issues under https://github.com/apache/arrow-datafusion/issues/6195 that might be interesting to do if you have time and inclination

**Comment by alamb** [comment]
https://github.com/apache/arrow-datafusion/issues/8274 for this week
