### ISSUE TITLE
Epic: Statistics improvements

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8227]
### Is your feature request related to a problem or challenge?

We would like to use "statistics" in our project for transformations that rely on the statisics being "correct" (e.g. that the there are no values outside the `min` and `max` range). 

DataFusion has several optimizations like this too that rely on statistics being correct such as skipping file scans with limits such as in https://github.com/apache/arrow-datafusion/blob/e54894c39202815b14d9e7eae58f64d3a269c165/datafusion/core/src/datasource/statistics.rs#L34-L33. There are also suggestions of additional such optimizations like https://github.com/apache/arrow-datafusion/issues/6672

However the current Statistics code seems to make it hard to manage the 'are the statistics exact and can they be guaranteed for transformations' (@crepererum  noted this quite some time ago on https://github.com/apache/arrow-datafusion/issues/5613). This has recently lead to several bugs such as
* https://github.com/apache/arrow-datafusion/pull/8049
* https://github.com/apache/arrow-datafusion/pull/8094

We would like to make it clearer what is known and what is an estimate is know (e.g. the min/max of row counts may be known, but the actual value may be an estimate after a filter). This is described in more detail on https://github.com/apache/arrow-datafusion/issues/8078

As we began exploring this concept we ran into several issues with Statistics and I think it is getting big enough to warrant its own tracking epic

Related items
- [ ] https://github.com/apache/arrow-datafusion/issues/8078
- [ ] https://github.com/apache/arrow-datafusion/issues/8133
- [ ] https://github.com/apache/arrow-datafusion/issues/8099
- [ ] https://github.com/apache/arrow-datafusion/issues/7490
- [ ] https://github.com/apache/arrow-datafusion/issues/5614
- [ ] https://github.com/apache/arrow-datafusion/issues/5613

### Additional context

This is somewhat related

**Comment by suremarc** [comment]
Recently I began looking into implementing #10316, and the proposed approach was to add per-partition statistics to `ExecutionPlan` and use the information to determine when the partitions have non-overlapping sort keys. However, I realized this requires #8078 to be implemented, as determining whether or not ranges overlap requires upper and lower bounds. 

According to @alamb's comment on #8078, the (then) current state of the `Statistics` code means than implementing #8078 is intractable as of now until other issues with the statistics code are resolved (it seems there were some attempts to simplify the statistics code that ended up not getting completed). 

I see that work on this epic has stalled since February, is there interest in continuing it? If so, I'm a willing contributor, but it'd help to know what needs to be done first, in particular if the `Statistics` code is still in need of some simplification.

**Comment by suremarc** [comment]
> If we have per-partition statistics, merging them will be problematic for NDV. Extrapolation techniques are not likely to work.

Ok, well I suppose we can keep the existing global statistics and add a new per-partition statistics method (that defaults to returning the global statistics for each partition). That would probably be a less invasive change too. 

Would be happy to discuss the details more over on #10316

**Comment by alamb** [comment]
> According to @alamb's comment on #8078, the (then) current state of the `Statistics` code means than implementing #8078 is intractable as of now until other issues with the statistics code are resolved (it seems there were some attempts to simplify the statistics code that ended up not getting completed).

Well, that may have also been my attempt / excuse :) -- especially if I didn't have enough time to work on it

> I see that work on this epic has stalled since February, is there interest in continuing it? If so, I'm a willing contributor, but it'd help to know what needs to be done first, in particular if the Statistics code is still in need of some simplification.

I personally think we should go about this from the other end: try to implement the analysis for https://github.com/apache/datafusion/issues/10316 -- and use that as a vehicle to make any additional `Statistics` improvements needed. I think it would help to motivate statistics improvements if we had a real usecase.

Thank you @suremarc and @findepi

**Comment by alamb** [comment]
The process has started in 
- https://github.com/apache/datafusion/pull/14699

**Comment by clflushopt** [comment]
Thanks for this issue @alamb I was actually looking for an EPIC that covers the work planned for statistics; since there's already work done as a followup for #14699 in #14896 I am wondering what else is left that I can take on with regards to this ? There's still the work necessary to finish #3929 i.e #4158 abd #4159 both seem to be relatively related and can benefit from the the redesign in #14699.

**Comment by alamb** [comment]
@clflushopt  I don't really know as I am not driving the statistics rework myself and thus don't have much visibility into what is planned 

The only remaining thing I know of that comes to mind is
- https://github.com/apache/datafusion/issues/8229

but that is more of an API exercise rather than algorithms. 

Another thing that comes to mind is to look at / extend the existing https://github.com/apache/datafusion/blob/main/datafusion/physical-expr/src/intervals/cp_solver.rs code / show how it is useful

I was playing around with duckdb this morning. Somehow it uses its constrait solver to simplify away redundant filters. For example, it correctly deduces `x > 1 AND x > 2 AND x > 3 AND x < 6 AND x < 7 AND x < 8` is the same as `x>3 AND x<6`

```sql
create table foo(x int);
D insert into foo values (1);
D insert into foo values (5);

D explain SELECT * from foo where x > 1 AND x > 2 AND x > 3 AND x < 6 AND x < 7 AND x < 8;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│         SEQ_SCAN          │
│    ────────────────────   │
│         Table: foo        │
│   Type: Sequential Scan   │
│       Projections: x      │
│    Filters: x>3 AND x<6   │
│                           │
│          ~1 Rows          │
└───────────────────────────┘
```

**Comment by adriangb** [comment]
I haven't been able to keep much track of the (amazing, far reaching) work on `StatisticsV2` but I have a couple of questions from my limited understanding:
- DataFusion will be able to populate stats from Parquet files by reading the Parquet metadata, right? Will it do so lazily or would it do it eagerly in one go?
- Can I give DataFusion pre-computed statistics? In particular I have some of the stats in a secondary index. Could I pull some of those stats and feed them into DataFusion to avoid it having to fetch parquet metadata to e.g. decide it can skip processing a file altogether? If I did feed in partial stats, would DataFusion be able to fetch the remainder e.g. for other columns or for files I didn't provide stats for?

**Comment by berkaysynnada** [comment]
> * DataFusion will be able to populate stats from Parquet files by reading the Parquet metadata, right? Will it do so lazily or would it do it eagerly in one go?

`infer_stats()` API of ParquetFormat looks well-implemented to me, but I haven't had the chance to practice it yet. I'm also not very familiar with how it integrates with the frontside. Any additional insights on this would be appreciated by me too:)

> * Can I give DataFusion pre-computed statistics? In particular I have some of the stats in a secondary index. Could I pull some of those stats and feed them into DataFusion to avoid it having to fetch parquet metadata to e.g. decide it can skip processing a file altogether? If I did feed in partial stats, would DataFusion be able to fetch the remainder e.g. for other columns or for files I didn't provide stats for?

I will be very surprised if such a trick is possible.

`StatisticsV2` refactor mainly aimed to improve the internal handling of statistical information, rather than modifying its integration with tables, optimizers etc. Those aspects remain unchanged

**Comment by adriangb** [comment]
Should we add https://github.com/apache/datafusion/issues/15809 to the list of issues?

**Comment by alamb** [comment]
> Should we add [#15809](https://github.com/apache/datafusion/issues/15809) to the list of issues?

Yes absolutely, please feel free to do so when you find other related items!

**Comment by gabotechs** [comment]
I added some integration tests that execute all TPC-DS queries on a reduced dataset and compare for each node the `Statistics` (what was expected) with the collected metrics (what actually happened).

The idea is to provide a way for people to identify gaps in the stats system with tests, so that people contributing to this effort can qualify their contributions with actual numbers (they should be seeing their accuracy scores for the TPC-DS queries getting higher)

- https://github.com/apache/datafusion/pull/20292

**Comment by paleolimbot** [comment]
In today's community sync I volunteered to review the state of statistics issues. Given that this is already a summary issue and contains a lot of context I'll do it here 🙂 .

The first thing I see are ongoing efforts to expand the types of inexactness that can be represented in statistics. The `Statistics` object exposed to the `ExecutionPlan` doesn't make use of the `Distrubtion`, which is the basis for propagating statistics through expressions. This means there are two independent means by which ranges of values are propagated, with the `Distribution`-based mechanism able to more accurately represent things like half-open ranges. A relevant issue is https://github.com/apache/datafusion/issues/14896 although https://github.com/apache/datafusion/issues/8078 is similar and has some more concrete suggestions about how we can get `Statistics` to actually use the distribution/interval API.

Another "this is how statistics are represented" issue is that their current representation they is expensive to copy. The PR to use an Arc should help ( https://github.com/apache/datafusion/pull/20570 ).

Something we discussed at the community call today is that statistics can't represent some data types. This applies to built-in types (structs, maps, and lists) and extension types (variant and geometry/geography). I see @adriangb has already made a stab at structs support (https://github.com/apache/datafusion/pull/20589)...I didn't see an issue created for that yet so I made one: https://github.com/apache/datafusion/issues/20707 . A related item that has popped up at least once is other types of statistics (e.g., average byte size https://github.com/apache/datafusion/pull/19963 ).

I also see the ongoing effort to implement `partition_statistics()` for the built-in operators. This seems like a huge milestone that is almost done! (One remaining PR: https://github.com/apache/datafusion/pull/16956 ).

Finally, a few statistics related PRs that seem like they might be close to merging (some duplicates from above):

- https://github.com/apache/datafusion/pull/20292
- https://github.com/apache/datafusion/pull/16956
- https://github.com/apache/datafusion/pull/20570
- https://github.com/apache/datafusion/pull/20391

**Comment by asolimando** [comment]
Hey @paleolimbot, https://github.com/apache/datafusion/pull/20926 is relevant and (I believe) in good shape after a few rounds of review, in case you have some bandwidth!

**Comment by gabotechs** [comment]
Had an idea for qualifying stats improvements:
- https://github.com/apache/datafusion/pull/23975

Hopefully that can help identify weak spots and attract easy contributions for improving stats estimation in the different operators.
