### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Nov 20, 2023

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8274]
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Try some different ways to communicate / coordinate int he community
2. Help provide an interesting summary of what is happening in DataFusion this week

I request anyone else who has plans like this for DataFusion could try something like this (maybe tickets are the best place 🤔 )

## Plans for this week personally:
- [ ] https://github.com/apache/arrow-datafusion/issues/8227 (specifically, https://github.com/apache/arrow-datafusion/issues/8229 as a step towards https://github.com/apache/arrow-datafusion/issues/8078)
- [ ] Edits to paper (improve language and get it under the page limit) https://github.com/apache/arrow-datafusion/issues/6782 with @ozankabak @Dandandan @yjshen and @JayjeetAtGithub  @sunchao and @viirya
- [ ] sqlparser release: https://github.com/sqlparser-rs/sqlparser-rs/issues/1030

## My plans for next week
- [ ] https://github.com/apache/arrow-datafusion/issues/8130, in support of memory explosion in HashJoin outputs: https://github.com/apache/arrow-datafusion/issues/7848 with @korowa 

Major projects I intend to help review and coordinate
- [ ] Make function packages more modular (make all BuiltInScalarFunctions ScalarUDFs): https://github.com/apache/arrow-datafusion/issues/8045 with @2010YOUY01  (help https://github.com/apache/arrow-datafusion/pull/8258)
- [ ] `ARRAY` function hardening:  https://github.com/apache/arrow-datafusion/issues/6980 / https://github.com/apache/arrow-datafusion/issues/7988with @jayzhan211 @Veeupup @edmondop and @xudong963
- [ ] Review any new ticket / bug reports

**Comment by alamb** [comment]
Reviews planned:

Arrow-rs
- [ ] https://github.com/apache/arrow-rs/pull/5100

DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/7581

**Comment by alamb** [comment]
Review Queue


DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8289
- [ ] https://github.com/apache/arrow-datafusion/pull/8281 (1k+ lines)
- [ ] https://github.com/apache/arrow-datafusion/pull/7581
- [ ] https://github.com/apache/arrow-datafusion/pull/8266#pullrequestreview-1738538700
- [ ] https://github.com/apache/arrow-datafusion/pull/8272
- [ ] https://github.com/apache/arrow-datafusion/pull/8271
- [ ] https://github.com/apache/arrow-datafusion/pull/8268
- [ ] https://github.com/apache/arrow-datafusion/pull/8251#issuecomment-1819149188
- [ ] https://github.com/apache/arrow-datafusion/pull/8193#issuecomment-1817239349
- [ ] https://github.com/apache/arrow-datafusion/pull/8269#issuecomment-1818963564

sqlparser-rs
- [x] https://github.com/sqlparser-rs/sqlparser-rs/pull/1048
- [x] https://github.com/sqlparser-rs/sqlparser-rs/pull/1032
- [x] https://github.com/sqlparser-rs/sqlparser-rs/pull/1045
- [x] https://github.com/sqlparser-rs/sqlparser-rs/pull/1036
- [x] https://github.com/sqlparser-rs/sqlparser-rs/pull/1051
- [x] https://github.com/sqlparser-rs/sqlparser-rs/pull/1044


DataFusion:

**Comment by alamb** [comment]
Next week's work: https://github.com/apache/arrow-datafusion/issues/8329
