### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Nov 27, 2023

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8329]
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Try some different ways to communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

It would be great if anyone else who has plans like this for DataFusion could try to make them visible somehow as well

## Plans for this week personally:
- [x] sqlparser release: https://github.com/sqlparser-rs/sqlparser-rs/issues/1030
- [ ] https://github.com/apache/arrow-datafusion/issues/8227 (specifically, https://github.com/apache/arrow-datafusion/issues/8229 as a step towards https://github.com/apache/arrow-datafusion/issues/8078)
- [x] Final edits + draft submission for https://github.com/apache/arrow-datafusion/issues/6782 with @ozankabak @Dandandan @yjshen and @JayjeetAtGithub  @sunchao and @viirya
- [x] File follow on tickets towards making function packages more modular: https://github.com/apache/arrow-datafusion/issues/8045 

## My plans for next week
- [ ] https://github.com/apache/arrow-datafusion/issues/8130, in support of memory explosion in HashJoin outputs: https://github.com/apache/arrow-datafusion/issues/7848 with @korowa 

Major projects I intend to help review and coordinate
- [ ] Next steps towards function packages more modular (make all BuiltInScalarFunctions ScalarUDFs): https://github.com/apache/arrow-datafusion/issues/8045 with @2010YOUY01 
- [ ] `ARRAY` function hardening:  https://github.com/apache/arrow-datafusion/issues/6980 / https://github.com/apache/arrow-datafusion/issues/7988with @jayzhan211 @Veeupup @edmondop and @xudong963
- [ ] Review any new ticket / bug reports 

# Algorithm for (my) prioritizing PRs
Note there are many [committers](https://arrow.apache.org/committers/) who can review and merge PRs as well, so this is not the priorities of the project as a whole, just the approximate algorithm I am using

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to stuff needed for InfluxDB (as I am employed by them)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality

The current strategically important projects in my head are:

* https://github.com/apache/arrow-datafusion/issues/7926
* https://github.com/apache/arrow-datafusion/issues/8045
* Improving performance of high cardinality aggregation

Note that adding new array functionality (e.g. https://github.com/apache/arrow-datafusion/issues/6980 and its children) is very low on my priority list, not because I don't think they are valuable, but because I think they are less valuable than the other projects going on

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements. 

If you propose adding new functionality, the review cycle will be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example)

**Comment by alamb** [comment]
Arrow-rs
- [ ] https://github.com/apache/arrow-rs/pull/5114

DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8268
- [ ] https://github.com/apache/arrow-datafusion/pull/8271
- [ ] https://github.com/apache/arrow-datafusion/pull/7581
- [ ] https://github.com/apache/arrow-datafusion/pull/8299
- [ ] https://github.com/apache/arrow-datafusion/issues/8302

sqlparser-rs
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1044
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1040

**Comment by alamb** [comment]
I am very backed up on reviews. I will try and work through them over the next few days

**Comment by alamb** [comment]
DataFusion
- [x] https://github.com/apache/arrow-datafusion/pull/8319#pullrequestreview-1752631786
- [ ] https://github.com/apache/arrow-datafusion/pull/8306
- [ ] https://github.com/apache/arrow-datafusion/pull/8291
- [ ] https://github.com/apache/arrow-datafusion/pull/8312
- [ ] https://github.com/apache/arrow-datafusion/pull/8268
- [ ] https://github.com/apache/arrow-datafusion/pull/8271
- [ ] https://github.com/apache/arrow-datafusion/pull/7581
- [ ] https://github.com/apache/arrow-datafusion/pull/8299
- [ ] https://github.com/apache/arrow-datafusion/issues/8302

**Comment by alamb** [comment]
I also want to make my algorithm for prioritizing PR reviews more visible, so adding it here (and will add to descriptions too). I want to point out we have many [committers](https://arrow.apache.org/committers/) who can review and merge PRs as well, so this is not the priorities of the project as a whole, just the approximate algorithm I am using

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to stuff needed for InfluxDB (as I am employed by them)
3. PRs for documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality

The current strategically important projects I am tracking are:

* https://github.com/apache/arrow-datafusion/issues/8227
* https://github.com/apache/arrow-datafusion/issues/7926
* https://github.com/apache/arrow-datafusion/issues/8045

Note that adding new array functionality (e.g. https://github.com/apache/arrow-datafusion/issues/6980 and its children) is very low on my priority list, not because I don't think they are valuable, but because I think they are less valuable than the other projects going on

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements. 

If you propose adding new functionality, the review cycle will be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example)

**Comment by alamb** [comment]
DataFusion
- [x] https://github.com/apache/arrow-datafusion/pull/8352
- [x] https://github.com/apache/arrow-datafusion/pull/8354
- [x] https://github.com/apache/arrow-datafusion/pull/8351#pullrequestreview-1755135780
- [ ] https://github.com/apache/arrow-datafusion/pull/8291


DataFusion: As time permits (lower priority)
- [ ] https://github.com/apache/arrow-datafusion/pull/8268
- [ ] https://github.com/apache/arrow-datafusion/pull/8271
- [ ] https://github.com/apache/arrow-datafusion/pull/7581
- [ ] https://github.com/apache/arrow-datafusion/pull/8299
- [ ] https://github.com/apache/arrow-datafusion/issues/8302

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8291
- [ ] https://github.com/apache/arrow-datafusion/pull/8331
- [ ] https://github.com/apache/arrow-datafusion/pull/8159

DataFusion: As time permits (lower priority)
- [ ] https://github.com/apache/arrow-datafusion/pull/8268
- [ ] https://github.com/apache/arrow-datafusion/pull/8271
- [ ] https://github.com/apache/arrow-datafusion/pull/7581
- [ ] https://github.com/apache/arrow-datafusion/issues/8302

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8331
- [ ] https://github.com/apache/arrow-datafusion/pull/8356


DataFusion: As time permits (lower priority)
- [ ] https://github.com/apache/arrow-datafusion/pull/8268
- [ ] https://github.com/apache/arrow-datafusion/pull/8271
- [ ] https://github.com/apache/arrow-datafusion/pull/7581
- [ ] https://github.com/apache/arrow-datafusion/issues/8302

**Comment by alamb** [comment]
> Thanks @alamb !
> 
> Many people have asked me how to get involved in the DataFusion community and what they can do for the project (Because I've previously promoted DataFusion on the Chinese social media). This summary is very helpful for them.

Thank you for this feedback. It is very helpful. Other than writing up more detailed tickets, do you know of other things that would help?

> I have pinned this issue to make it easy for everyone to view.

I saw this -- that was very cool. Thank you. I will pin future such issues. 

> Express gratitude once again for all that you have done for the community.

Thank you very much @jackwener  - I am always amazed by all the work we do together.

**Comment by alamb** [comment]
Next Week: https://github.com/apache/arrow-datafusion/issues/8420
