### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Dec 4, 2023

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8420]
Follow on to [Nov 27 2023](https://github.com/apache/arrow-datafusion/issues/8329):

## Boilerplate Overview
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Try some different ways to communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

It would be great if anyone else who has plans like this for DataFusion could try to make them visible somehow as well

## My (personal) plans for this week
- [ ] Complete https://github.com/apache/arrow-datafusion/issues/8376
- [ ] Reproduce and file several bugs / limitations we have hit in Influx recently (udpate: https://github.com/apache/arrow-datafusion/issues/8451)

## Project Queue (list of future projects)
- [ ] https://github.com/apache/arrow-datafusion/issues/8227 (specifically, https://github.com/apache/arrow-datafusion/issues/8229 as a step towards https://github.com/apache/arrow-datafusion/issues/8078)
- [ ] https://github.com/apache/arrow-datafusion/issues/8130, in support of memory explosion in HashJoin outputs: https://github.com/apache/arrow-datafusion/issues/7848 with @korowa 

## Additional major projects I hope to help review and coordinate
- [ ] Next steps towards function packages more modular (make all BuiltInScalarFunctions ScalarUDFs): https://github.com/apache/arrow-datafusion/issues/8045 with @2010YOUY01 . This week I hope to get https://github.com/apache/arrow-datafusion/pull/8046 mergable, which would require https://github.com/apache/arrow-datafusion/issues/8157)
- [ ] `ARRAY` function hardening:  https://github.com/apache/arrow-datafusion/issues/6980 / https://github.com/apache/arrow-datafusion/issues/7988 
- [ ] Review any new ticket / bug reports 

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can review and merge PRs as well, so this is not the priorities of the project as a whole, just the approximate algorithm I am using

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (as I am employed by them)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality

The current strategically important projects in my head are:

* https://github.com/apache/arrow-datafusion/issues/8045
* Improving performance of high cardinality aggregation

Note that adding new array functionality (e.g. https://github.com/apache/arrow-datafusion/issues/6980 and its children) is very low on my priority list, not because I don't think they are valuable, but because I think they are less valuable than the other projects going on - it would be great if other people could help pick these up too. 

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation / etc. 

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example)

**Comment by alamb** [comment]
Review Queue:

sqlparser-rs:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1063
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1062

**Comment by alamb** [comment]
Review Queue:

DataFusion:
- [x] https://github.com/apache/arrow-datafusion/pull/8424
- [x] https://github.com/apache/arrow-datafusion/pull/8414

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5178


sqlparser-rs:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1063
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1062

**Comment by alamb** [comment]
DataFusion:
- [ ] https://github.com/apache/arrow-datafusion/pull/8413
- [ ] https://github.com/apache/arrow-datafusion/pull/8268

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5178


sqlparser-rs:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1063
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1062

**Comment by alamb** [comment]
Next week tracked in https://github.com/apache/arrow-datafusion/issues/8490
