### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Dec 11, 2023 #8420

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8490]
Follow on to [Dec 4 2023](https://github.com/apache/arrow-datafusion/issues/8420):

## Boilerplate Overview
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Try some different ways to communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

It would be great if anyone else who has plans like this for DataFusion could try to make them visible somehow as well

## My (personal) plans for this week
- [ ] Shepherd the PRs through https://github.com/apache/arrow-datafusion/issues/8376
- [ ] Fix https://github.com/apache/arrow-datafusion/issues/8451)
- [ ] Draft a proposal to move DataFusion to a new top level project: https://github.com/apache/arrow-datafusion/discussions/6475
- [ ] Reproduce other bugs / limitations we have hit while upgrading DataFusion in InfluxDB IOx 

## Project Queue (list of future projects)
- [ ] https://github.com/apache/arrow-datafusion/issues/8130, in support of memory explosion in HashJoin outputs: https://github.com/apache/arrow-datafusion/issues/7848 
- [ ] https://github.com/apache/arrow-datafusion/issues/8227 (specifically, https://github.com/apache/arrow-datafusion/issues/8229 as a step towards https://github.com/apache/arrow-datafusion/issues/8078)

## Projects I hope to help review and coordinate
- [ ] Next steps towards function packages more modular (make all BuiltInScalarFunctions ScalarUDFs): https://github.com/apache/arrow-datafusion/issues/8045 with @2010YOUY01 and @edmondop . This week I hope to help get https://github.com/apache/arrow-datafusion/issues/8157 complete, and move on to https://github.com/apache/arrow-datafusion/pull/8046
- [ ] Review any new ticket / bug reports 

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I am using

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality

The current strategically important projects in my head are:

* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 
* Improving performance of high cardinality aggregation (I have dreams of working on this over christmas break)

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation / etc. 

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

**Comment by alamb** [comment]
Review Queue



sqlparser-rs:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1063
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1062

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8520
- [ ] https://github.com/apache/arrow-datafusion/pull/8477
- [ ] https://github.com/apache/arrow-datafusion/pull/8317
- [ ] https://github.com/apache/arrow-datafusion/pull/8482
- [ ] https://github.com/apache/arrow-datafusion/pull/8489

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5196
- [ ] https://github.com/apache/arrow-rs/pull/5186


sqlparser-rs:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1063
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1062

**Comment by alamb** [comment]
Datafusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8520
- [ ] https://github.com/apache/arrow-datafusion/pull/8317
- [ ] https://github.com/apache/arrow-datafusion/pull/8489
- [ ] https://github.com/apache/arrow-datafusion/pull/8494

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5186


sqlparser-rs:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1063
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1062

**Comment by alamb** [comment]
Datafusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8538
- [ ] https://github.com/apache/arrow-datafusion/pull/8317
- [ ] https://github.com/apache/arrow-datafusion/pull/8489
- [ ] https://github.com/apache/arrow-datafusion/pull/8494

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5186


sqlparser-rs:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1063
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1062

**Comment by alamb** [comment]
Datafusion
- [x] https://github.com/apache/arrow-datafusion/pull/8546#pullrequestreview-1783925698
- [ ] https://github.com/apache/arrow-datafusion/pull/8538
- [ ] https://github.com/apache/arrow-datafusion/pull/8317

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5186


sqlparser-rs:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1063
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1062

**Comment by Xuanwo** [comment]
The weekly project plan looks great! Are you updating this manually or using a tool?

**Comment by alamb** [comment]
> The weekly project plan looks great! Are you updating this manually or using a tool?

I am creating these manually @Xuanwo  -- though now what I do is copy the last weeks's description to the next week, and update the text rather than writing it from scratch each time.

**Comment by alamb** [comment]
Datafusion
- [x] https://github.com/apache/arrow-datafusion/pull/7862#pullrequestreview-1785174973
- [ ]  https://github.com/apache/arrow-datafusion/pull/8558
- [ ] https://github.com/apache/arrow-datafusion/pull/8317

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5186


sqlparser-rs:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1063
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1062

**Comment by alamb** [comment]
https://github.com/apache/arrow-datafusion/issues/8577 for next week
