### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Dec 25, 2023

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8655]
Follow on to [Dec 18 2023](https://github.com/apache/arrow-datafusion/issues/8577):

## Boilerplate Overview
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Try some different ways to communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

It would be great if anyone else who has plans like this for DataFusion could try to make them visible somehow as well

## My (personal) plans for this week
- [ ] https://github.com/apache/arrow-datafusion/issues/8491 
- [x] Shepherd final Bloom Filter clean up PRs: https://github.com/apache/arrow-datafusion/pull/8442

## Project Queue (list of future projects)
- [ ] https://github.com/apache/arrow-datafusion/issues/6780
- [ ] https://github.com/apache/arrow-datafusion/issues/8227 (specifically, https://github.com/apache/arrow-datafusion/issues/8078)

## Projects I hope to help review and coordinate
- [ ] Memory explosion in HashJoin outputs: https://github.com/apache/arrow-datafusion/issues/7848  from @korowa 
- [ ] Making function packages more modular: https://github.com/apache/arrow-datafusion/issues/8045
- [ ] Improve planning speed https://github.com/apache/arrow-datafusion/issues/5637 (e.g with benchmarks https://github.com/apache/arrow-datafusion/issues/8638 )

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I am using

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality

The current strategically important projects in my head are:

* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 
* Improving performance of high cardinality aggregation (I have dreams of working on this over Christmas break)

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation / etc. 

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8562
- [ ] https://github.com/apache/arrow-datafusion/pull/8558
- [ ] https://github.com/apache/arrow-datafusion/pull/7581

**Comment by alamb** [comment]
DataFusion
- [x] https://github.com/apache/arrow-datafusion/pull/8653
- [x] https://github.com/apache/arrow-datafusion/pull/8654
- [ ] https://github.com/apache/arrow-datafusion/pull/8562
- [ ] https://github.com/apache/arrow-datafusion/pull/8558
- [ ] https://github.com/apache/arrow-datafusion/pull/7581

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8658
- [ ] https://github.com/apache/arrow-datafusion/pull/8562
- [ ] https://github.com/apache/arrow-datafusion/issues/8668
- [ ] https://github.com/apache/arrow-datafusion/pull/7581

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8675
- [ ] https://github.com/apache/arrow-datafusion/pull/8669
- [ ] https://github.com/apache/arrow-datafusion/pull/8667
- [ ] https://github.com/apache/arrow-datafusion/pull/8562
- [ ] https://github.com/apache/arrow-datafusion/pull/8636
- [ ] https://github.com/apache/arrow-datafusion/pull/8659
- [ ] https://github.com/apache/arrow-datafusion/pull/8664#issuecomment-1871219638
- [ ] https://github.com/apache/arrow-datafusion/pull/7581
- [ ] https://github.com/apache/arrow-datafusion/pull/8625#pullrequestreview-1797135821

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5249

**Comment by alamb** [comment]
DataFusion
- [x] https://github.com/apache/arrow-datafusion/pull/8695/files
- [ ] https://github.com/apache/arrow-datafusion/pull/8672
- [ ] https://github.com/apache/arrow-datafusion/pull/8562
- [ ] https://github.com/apache/arrow-datafusion/pull/8636
- [ ] https://github.com/apache/arrow-datafusion/pull/8659
- [ ] https://github.com/apache/arrow-datafusion/pull/8664#issuecomment-1871219638
- [ ] https://github.com/apache/arrow-datafusion/pull/7581
- [ ] https://github.com/apache/arrow-datafusion/pull/8625#pullrequestreview-1797135821

**Comment by alamb** [comment]
Next up: https://github.com/apache/arrow-datafusion/issues/8704
