### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Jan 1, 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8704]
Follow on to [Dec 25 2023](https://github.com/apache/arrow-datafusion/issues/8655):

## Boilerplate Overview
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Try some different ways to communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

*It would be great if anyone else who has plans like this for DataFusion could try to make them visible somehow as well* 🙏  (feel free to copy / modify the format)

## My (personal) plans for this week
- [x] Circulate / Discuss: https://github.com/apache/arrow-datafusion/issues/8491 
- [ ] Prepare next steps for https://github.com/apache/arrow-datafusion/issues/8045

## Project Queue (list of future projects)
- [ ] Help with some more advanced pruning predicates https://github.com/apache/arrow-datafusion/issues/7869#issuecomment-1872530149
- [ ] Writing: https://github.com/apache/arrow-datafusion/issues/6780
- [ ] Statistics: https://github.com/apache/arrow-datafusion/issues/8227 (specifically, https://github.com/apache/arrow-datafusion/issues/8078)

## Projects I plan to prioritize reviewing / helping
- [ ] Additional work on `PruningPredicate`: https://github.com/apache/arrow-datafusion/pull/8669 from @yahoNanJing, and  possibly https://github.com/apache/arrow-datafusion/issues/7869#issuecomment-1872530149 with @NGA-TRAN 
- [ ] Memory explosion in HashJoin outputs: https://github.com/apache/arrow-datafusion/issues/7848  from @korowa 
- [ ] Improve planning speed https://github.com/apache/arrow-datafusion/issues/5637 with @matthewmturner 
- [ ] Making function packages more modular: https://github.com/apache/arrow-datafusion/issues/8045 (looking for help)

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I am using

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality

The current strategically important projects in my head are:

* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 
* Improving performance of high cardinality aggregation (I have dreams of working on this over Christmas break)

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation / etc. 

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

**Comment by alamb** [comment]
Review Queue:

Arrow-rs:
- [ ] https://github.com/apache/arrow-rs/pull/5262

**Comment by alamb** [comment]
Review Queue:

DataFusion:
- [x] https://github.com/apache/arrow-datafusion/pull/8715#pullrequestreview-1800363039

Arrow-rs:
- [ ] https://github.com/apache/arrow-rs/pull/5262

**Comment by alamb** [comment]
DataFusion 
- [ ] https://github.com/apache/arrow-datafusion/pull/8721

**Comment by jayzhan211** [comment]
btw, the title should be Jan 1, 2024 :)

**Comment by alamb** [comment]
> btw, the title should be Jan 1, 2024 :)

Thank you @jayzhan211  -- I have fixed it (off by one, a classic programmer error 😆 )

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/issues/8723
- [ ] https://github.com/apache/arrow-datafusion/pull/8562
- [ ] https://github.com/apache/arrow-datafusion/pull/8566

**Comment by alamb** [comment]
DataFUsion:
- [x] https://github.com/apache/arrow-datafusion/pull/8774#pullrequestreview-1807481671
- [ ] https://github.com/apache/arrow-datafusion/pull/8775
- [ ] https://github.com/apache/arrow-datafusion/pull/8744
