### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Jan 8, 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8786]
Follow on to [Jan 1, 2024](https://github.com/apache/arrow-datafusion/issues/8704)

## Boilerplate Overview
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Try some different ways to communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

*It would be great if anyone else who has plans like this for DataFusion could try to make them visible somehow as well* 🙏  (feel free to copy / modify the format)

## My (personal) plans for this week
- [ ] Work on more advanced pruning predicates https://github.com/apache/arrow-datafusion/issues/7869#issuecomment-1872530149
- [ ] Work on a blog post about DataFusion: https://github.com/apache/arrow-site/pull/457
- [ ] Prepare next steps for making function packages more modular https://github.com/apache/arrow-datafusion/issues/8045

## Project Queue (list of future projects)
- [ ] Statistics: https://github.com/apache/arrow-datafusion/issues/8227 (specifically, https://github.com/apache/arrow-datafusion/issues/8078)

## Projects I plan to prioritize reviewing / helping
- [ ] Memory explosion in HashJoin outputs: https://github.com/apache/arrow-datafusion/issues/7848  from @korowa 
- [ ] Improve planning speed https://github.com/apache/arrow-datafusion/issues/5637 with @matthewmturner 
- [ ] Making function packages more modular: https://github.com/apache/arrow-datafusion/issues/8045 (looking for help)

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I am using

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality

The current strategically important projects in my head are:

* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 
* [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* [Improving performance of aggregation ](https://github.com/apache/arrow-datafusion/issues/7000) - especially high cardinality groupings, where we still lag state of the art by 2x

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation / etc. 

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8744
- [ ] https://github.com/apache/arrow-datafusion/pull/8733
- [ ] https://github.com/apache/arrow-datafusion/pull/8566

**Comment by matthewmturner** [comment]
@alamb FYI I am away for a few days and then will get back into this.

**Comment by matthewmturner** [comment]
I had in mind checking for more places to replace results with boolean and then seeing if I could extract some of the optimization ideas from @zeodotr on #7698. Or are you keen to make the DFSchema cheaper to copy?

**Comment by alamb** [comment]
> I had in mind checking for more places to replace results with boolean and then seeing if I could extract so

I think that is the best idea. I would personally suggest focusing on the planning benchmarks and trying to improve whatever they show as the tall pole

**Comment by matthewgapp** [comment]
@alamb just bumping the recursive CTE PR :) https://github.com/apache/arrow-datafusion/pull/7581 

I fixed an issue that was raised and brought it up to date with main.

**Comment by alamb** [comment]
DataFusion tomorrow
- [ ] https://github.com/apache/arrow-datafusion/pull/8785
- [ ] https://github.com/apache/arrow-datafusion/pull/8771
- [ ] https://github.com/apache/arrow-datafusion/pull/8780
- [ ] https://github.com/apache/arrow-datafusion/pull/8744
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/issues/8786

**Comment by alamb** [comment]
> @alamb just bumping the recursive CTE PR :) #7581
> 
> I fixed an issue that was raised and brought it up to date with main.

Thank you @matthewgapp -- I keep hoping someone else can help with that review too that has an interest in recursive CTEs. I'll try and take a look later today

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8771
- [ ] https://github.com/apache/arrow-datafusion/pull/8566

**Comment by maruschin** [comment]
@alamb hi, сould you suggest an area where to direct my attention. I spend a lot of time looking for issue to start working on.

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/issues/8789#issuecomment-1883818447
- [ ] https://github.com/apache/arrow-datafusion/pull/8771
- [ ] https://github.com/apache/arrow-datafusion/pull/7893
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/8744
- [ ] https://github.com/apache/arrow-datafusion/pull/8771


DataFusion Next
- [ ] https://github.com/apache/arrow-datafusion/pull/8823
- [ ] https://github.com/apache/arrow-datafusion/pull/8780

**Comment by alamb** [comment]
> @alamb hi, сould you suggest an area where to direct my attention. I spend a lot of time looking for issue to start working on.

Thanks @maruschin ! 

If you have time, looking into the bug report here https://github.com/apache/arrow-datafusion/issues/8819 would be super helpful 

Debugging this report https://github.com/apache/arrow-datafusion/issues/8702 would also be helpful (as would in general making the datafusion-cli output generation code simpler)


There is also supporting partitioned writing that seems like it would be great to implement: https://github.com/apache/arrow-datafusion/issues/8493

**Comment by alamb** [comment]
Review Queue:

DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8835
- [ ] https://github.com/apache/arrow-datafusion/pull/8780
- [ ] https://github.com/apache/arrow-datafusion/pull/7893
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/8744

**Comment by alamb** [comment]
Done in https://github.com/apache/arrow-datafusion/issues/8864
