### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Jan 15, 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8864]
Follow on to [Jan 8, 2024](https://github.com/apache/arrow-datafusion/issues/8786)

## Boilerplate Introduction
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**It would be great for other contributors to DataFusion who plan non trivial work could try to make them visible somehow as well** 🙏  (feel free to copy / modify the format)

## My (personal) plans for this week
- [ ] Complete blog post about DataFusion: https://github.com/apache/arrow-site/pull/457
- [ ] Complete some performance work (https://github.com/apache/arrow-datafusion/issues/7064) + benchmarking (https://github.com/apache/arrow-datafusion/issues/8860 and https://github.com/apache/arrow-datafusion/issues/8791
- [ ] (Stretch) Prepare next steps for making function packages more modular https://github.com/apache/arrow-datafusion/issues/8045

## Project Queue (list of future projects)
- [ ] More advanced pruning predicates https://github.com/apache/arrow-datafusion/issues/7869
- [ ] Statistics: https://github.com/apache/arrow-datafusion/issues/8227 (specifically, https://github.com/apache/arrow-datafusion/issues/8078)

## Projects I plan to prioritize reviewing / helping
- [ ] Memory explosion in HashJoin outputs: https://github.com/apache/arrow-datafusion/issues/7848  from @korowa 
- [ ] Improve planning speed https://github.com/apache/arrow-datafusion/issues/5637 with @matthewmturner 
- [ ] Making function packages more modular: https://github.com/apache/arrow-datafusion/issues/8045 (thank you @guojidan)
- [ ] Supporting recursive CTEs https://github.com/apache/arrow-datafusion/issues/462 with @matthewgapp  and @jonahgao

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The current strategically important projects in my head are:

* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 
* [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* [Improving performance of aggregation ](https://github.com/apache/arrow-datafusion/issues/7000) - especially high cardinality groupings, where we still lag state of the art by 2x

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

**Comment by alamb** [comment]
Next week covered in https://github.com/apache/arrow-datafusion/issues/8864

**Comment by alamb** [comment]
Review Queue:

DataFusion
- [x] https://github.com/apache/arrow-datafusion/pull/8834
- [ ] https://github.com/apache/arrow-datafusion/pull/8833
- [x] https://github.com/apache/arrow-datafusion/pull/8843
- [ ] https://github.com/apache/arrow-datafusion/pull/8842
- [ ] https://github.com/apache/arrow-datafusion/pull/8841
- [ ] https://github.com/apache/arrow-datafusion/pull/8720
- [ ] https://github.com/apache/arrow-datafusion/pull/8835
- [ ] https://github.com/apache/arrow-datafusion/pull/8780
- [ ] https://github.com/apache/arrow-datafusion/pull/7893
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/8744

**Comment by alamb** [comment]
DataFusion: 
- [ ] https://github.com/apache/arrow-datafusion/pull/8841
- [ ] https://github.com/apache/arrow-datafusion/pull/7893
- [ ] https://github.com/apache/arrow-datafusion/pull/8862
- [ ] https://github.com/apache/arrow-datafusion/pull/8780
- [ ] https://github.com/apache/arrow-datafusion/pull/8850
- [ ] https://github.com/apache/arrow-datafusion/pull/8833
- [ ] https://github.com/apache/arrow-datafusion/pull/8720
- [ ] https://github.com/apache/arrow-datafusion/pull/8835
- [ ] https://github.com/apache/arrow-datafusion/pull/8566

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8888
- [ ] https://github.com/apache/arrow-datafusion/pull/8892
- [ ] https://github.com/apache/arrow-datafusion/pull/8886
- [ ] https://github.com/apache/arrow-datafusion/pull/8891
- [ ] https://github.com/apache/arrow-datafusion/pull/8780
- [ ] https://github.com/apache/arrow-datafusion/pull/8835
- [ ] https://github.com/apache/arrow-datafusion/pull/8850
- [ ] https://github.com/apache/arrow-datafusion/pull/8862
- [ ] https://github.com/apache/arrow-datafusion/pull/8344
- [ ] https://github.com/apache/arrow-datafusion/pull/7893
- [ ] https://github.com/apache/arrow-datafusion/pull/8720
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/8829
- [ ] https://github.com/apache/arrow-datafusion/pull/8839

Sqlparser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1093
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1096

**Comment by alamb** [comment]
Next week: https://github.com/apache/arrow-datafusion/issues/8933
