### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Jan 22, 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8933]
Follow on to [Jan 15, 2024](https://github.com/apache/arrow-datafusion/issues/8864)

## Boilerplate Introduction
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**It would be great for other contributors to DataFusion who plan non trivial work could try to make them visible somehow as well** 🙏  (feel free to copy / modify the format)

## My (personal) plans for this week
- [x] Help test / optimize HashJoin outputs generation: https://github.com/apache/arrow-datafusion/pull/8020  from @korowa 
- [x] Complete https://github.com/apache/arrow-datafusion/pull/8849 with @jayzhan211 
- [ ] Begin work on https://github.com/apache/arrow-datafusion/issues/7064
- [ ] Get first steps towards breaking up packages https://github.com/apache/arrow-datafusion/pull/8705 reviewed, address comments, file follow on tickets

## Project Queue (list of future projects)
- [ ] Improved Statistics: https://github.com/apache/arrow-datafusion/issues/8227 (specifically, https://github.com/apache/arrow-datafusion/issues/8078)

## Projects I am prioritizing reviewing / helping
- [ ] More advanced pruning predicates https://github.com/apache/arrow-datafusion/issues/7869 with @appletreeisyellow 
- [ ] Improve planning speed https://github.com/apache/arrow-datafusion/issues/5637 with @matthewmturner 
- [ ] Supporting various work to improve user defined functions and make functions packages more modular: https://github.com/apache/arrow-datafusion/issues/8045 (thank you @guojidan)
- [x] Supporting recursive CTEs https://github.com/apache/arrow-datafusion/issues/462 with @matthewgapp  and @jonahgao

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The current strategically important projects in my head are:

* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 
* [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* [Improving performance of aggregation ](https://github.com/apache/arrow-datafusion/issues/7000) - especially high cardinality groupings, where we still lag state of the art by 2x

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

**Comment by alamb** [comment]
Review Queue:
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8905
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/8908
- [ ] https://github.com/apache/arrow-datafusion/pull/7893

Sqlparser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1093
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1096
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1099
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1061

Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8780

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8848
- [ ] https://github.com/apache/arrow-datafusion/pull/8930
- [ ] https://github.com/apache/arrow-datafusion/pull/8840
- [ ] https://github.com/apache/arrow-datafusion/pull/8947
- [ ] https://github.com/apache/arrow-datafusion/pull/8902
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/8908
- [ ] https://github.com/apache/arrow-datafusion/pull/7893

Sqlparser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1093
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1096
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1099
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1061


Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8780
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8941
- [ ] https://github.com/apache/arrow-datafusion/pull/8840
- [ ] https://github.com/apache/arrow-datafusion/pull/8946
- [ ] https://github.com/apache/arrow-datafusion/pull/8902
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/7893

Sqlparser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1093
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1099
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1061


Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8780
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

**Comment by alamb** [comment]
DataFusion 
- [ ] https://github.com/apache/arrow-datafusion/pull/8977
- [ ] https://github.com/apache/arrow-datafusion/pull/8982
- [ ] https://github.com/apache/arrow-datafusion/pull/8960
- [ ] https://github.com/apache/arrow-datafusion/pull/8780
- [ ] https://github.com/apache/arrow-datafusion/pull/8840
- [ ] https://github.com/apache/arrow-datafusion/pull/8946
- [ ] https://github.com/apache/arrow-datafusion/pull/8902
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/7893

Arrow

Sqlparser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1110
- [ ] https://github.com/apache/arrow-rs/pull/5318

Watching

**Comment by alamb** [comment]
DataFusion: 
- [ ] https://github.com/apache/arrow-datafusion/pull/8985

**Comment by gruuya** [comment]
Can we also add https://github.com/apache/arrow-datafusion/pull/8894 to the queue please?

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8940
- [ ] https://github.com/apache/arrow-datafusion/pull/8939
- [ ] https://github.com/apache/arrow-datafusion/pull/8894
- [ ] https://github.com/apache/arrow-datafusion/pull/8967
- [ ] https://github.com/apache/arrow-datafusion/pull/8817
- [ ] https://github.com/apache/arrow-datafusion/pull/8840
- [ ] https://github.com/apache/arrow-datafusion/pull/8946
- [ ] https://github.com/apache/arrow-datafusion/pull/8902
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/7893

Sqlparser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1110

Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

**Comment by alamb** [comment]
> Can we also add #8894 to the queue please?

FYI @gruuya  -- I plan to do a sqlparser release today or tomorrow, so we should be able to get that integrated into DataFusion over the next few days and get #8894  mergeable

**Comment by gruuya** [comment]
> I plan to do a sqlparser release today or tomorrow, so we should be able to get that integrated into DataFusion over the next few days and get https://github.com/apache/arrow-datafusion/pull/8894 mergeable

Sounds good, thanks!

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8840
- [ ] https://github.com/apache/arrow-datafusion/pull/8946
- [ ] https://github.com/apache/arrow-datafusion/pull/9012
- [ ] https://github.com/apache/arrow-datafusion/pull/8902
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/7893
- [ ] https://github.com/apache/arrow-datafusion/pull/8953
- [ ] https://github.com/apache/arrow-datafusion/pull/8939

Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

**Comment by alamb** [comment]
- [ ] https://github.com/apache/arrow-datafusion/pull/9014
- [ ] https://github.com/apache/arrow-datafusion/pull/9013

**Comment by alamb** [comment]
Next week: https://github.com/apache/arrow-datafusion/issues/9030
