### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Jan 29, 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9030]
Follow on to [Jan 22, 2024](https://github.com/apache/arrow-datafusion/issues/8933)

## Boilerplate Introduction
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**It would be great for other contributors to DataFusion who plan non trivial work could try to make them visible somehow as well** 🙏  (feel free to copy / modify the format)

## My (personal) plans for this week
- [ ] (LOOKING FOR A REVIEW HERE) Get first step of breaking out functions ://github.com/apache/arrow-datafusion/pull/8705 reviewed, address comments, file follow on tickets
- [x] Complete https://github.com/apache/arrow-datafusion/pull/8849 with @jayzhan211 
- [ ] Continue work to improve ClickBench performance https://github.com/apache/arrow-datafusion/issues/7064

## Project Queue (list of future projects)
- [ ] Improved Statistics: https://github.com/apache/arrow-datafusion/issues/8227 (specifically, https://github.com/apache/arrow-datafusion/issues/8078)

## Projects I plan to help actively help review / plan
- [ ] More advanced pruning predicates https://github.com/apache/arrow-datafusion/issues/7869 with @appletreeisyellow 
- [ ] Improve planning speed https://github.com/apache/arrow-datafusion/issues/5637 with @matthewmturner 
- [ ] Hardening Recursive CTEs https://github.com/apache/arrow-datafusion/issues/462 with @matthewgapp  and @jonahgao

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as improved / expanded tests, etc
* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 
* [Improving performance of aggregation ](https://github.com/apache/arrow-datafusion/issues/7000) - especially high cardinality groupings, where we still lag state of the art by 2x

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

**Comment by alamb** [comment]
Review Queue:

DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9014
- [ ] https://github.com/apache/arrow-datafusion/pull/8946
- [ ] https://github.com/apache/arrow-datafusion/pull/8902
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/7893

Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

**Comment by alamb** [comment]
Review Queue:

DataFusion
- [x] https://github.com/apache/arrow-datafusion/pull/9014
- [x] https://github.com/apache/arrow-datafusion/pull/9027#pullrequestreview-1847532194
- [ ] https://github.com/apache/arrow-datafusion/pull/9020
- [ ] https://github.com/apache/arrow-datafusion/pull/8664
- [ ] https://github.com/apache/arrow-datafusion/pull/8753
- [ ] https://github.com/apache/arrow-datafusion/pull/8946
- [ ] https://github.com/apache/arrow-datafusion/pull/8902
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/7893

Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9066
- [ ] https://github.com/apache/arrow-datafusion/pull/9048
- [ ] https://github.com/apache/arrow-datafusion/pull/8891
- [ ] https://github.com/apache/arrow-datafusion/pull/8664
- [ ] https://github.com/apache/arrow-datafusion/pull/8753
- [ ] https://github.com/apache/arrow-datafusion/pull/8902
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/7893

Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8985
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9073#pullrequestreview-1853517046
- [ ] https://github.com/apache/arrow-datafusion/pull/9064
- [ ] https://github.com/apache/arrow-datafusion/pull/9019
- [ ] https://github.com/apache/arrow-datafusion/pull/8902
- [ ] https://github.com/apache/arrow-datafusion/pull/9069
- [ ] https://github.com/apache/arrow-datafusion/pull/8753
- [ ] https://github.com/apache/arrow-datafusion/pull/8902
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/7893
- [ ] https://github.com/apache/arrow-datafusion/pull/8664
- [ ] https://github.com/apache/arrow-datafusion/pull/8891


Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8985
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9019
- [ ] https://github.com/apache/arrow-datafusion/pull/8753
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/7893
- [ ] https://github.com/apache/arrow-datafusion/pull/8664
- [ ] https://github.com/apache/arrow-datafusion/pull/8891
- [ ] https://github.com/apache/arrow-datafusion/pull/8271


Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/9064
- [ ] https://github.com/apache/arrow-datafusion/pull/8985
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

**Comment by alamb** [comment]
Next week in https://github.com/apache/arrow-datafusion/issues/9121
