### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Feb 5, 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9121]
Follow on to [Jan 29, 2024](https://github.com/apache/arrow-datafusion/issues/9030)

Note: I will be traveling this week so I will likely have less time to devote to DataFusion

## Boilerplate Introduction
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**It would be great for other contributors to DataFusion who plan non trivial work could try to make them visible somehow as well** 🙏  (feel free to copy / modify the format)

## My (personal) goals for this project
1000 projects are built using DataFusion 📈 

## My (personal) plans for this week
- [x] Continue work to break out functions (e.g. `datafusion-functions-array` crate) https://github.com/apache/arrow-datafusion/pull/9113 and related infrastructure https://github.com/apache/arrow-datafusion/pull/9075
- [ ] Continue to improve ClickBench performance [Faster String Aggregation](https://github.com/apache/arrow-datafusion/issues/7064) (this is my personal fun project)
- [ ] More advanced pruning predicates https://github.com/apache/arrow-datafusion/issues/7869 with @appletreeisyellow 

## Project Queue (list of future projects)
- [ ] Improved Statistics: https://github.com/apache/arrow-datafusion/issues/8227 (specifically, https://github.com/apache/arrow-datafusion/issues/8078)

## Projects I plan to help actively help review / plan
- [ ] Improve planning speed https://github.com/apache/arrow-datafusion/issues/5637 with @matthewmturner 
- [ ] Hardening Recursive CTEs https://github.com/apache/arrow-datafusion/issues/462 with @matthewgapp  and @jonahgao

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 
* [Improving performance of aggregation ](https://github.com/apache/arrow-datafusion/issues/7000) - especially high cardinality groupings, where we still lag state of the art by 2x

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

**Comment by alamb** [comment]
Review Queue

DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9064
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/7893
- [ ] https://github.com/apache/arrow-datafusion/pull/8664
- [ ] https://github.com/apache/arrow-datafusion/pull/8891
- [ ] https://github.com/apache/arrow-datafusion/pull/8271


Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8985
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9080
- [ ] https://github.com/apache/arrow-datafusion/pull/9064
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/7893
- [ ] https://github.com/apache/arrow-datafusion/pull/8664
- [ ] https://github.com/apache/arrow-datafusion/pull/8891
- [ ] https://github.com/apache/arrow-datafusion/pull/8271


Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8985
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

Sqlparser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1122

**Comment by alamb** [comment]
DataFusion

- [ ] https://github.com/apache/arrow-datafusion/pull/8891
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/8664
- [ ] https://github.com/apache/arrow-datafusion/pull/8271

Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8985
- [ ] https://github.com/apache/arrow-datafusion/pull/8905


Sqlparser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1122

**Comment by r3stl355** [comment]
@alamb how did you make your checkboxes read-only and non-movable. I tried few options but end up with a list in which items can be moved around and boxes ticked/unticked without editing the issue. Thanks

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9129
- [ ] https://github.com/apache/arrow-datafusion/pull/9163#
- [ ] https://github.com/apache/arrow-datafusion/pull/9108
- [ ] https://github.com/apache/arrow-datafusion/pull/8891#issuecomment-1932021143
- [ ] https://github.com/apache/arrow-datafusion/pull/9127
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/8664
- [ ] https://github.com/apache/arrow-datafusion/pull/8271

Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8985
- [ ] https://github.com/apache/arrow-datafusion/pull/8891
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

Sqlparser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1122

**Comment by alamb** [comment]
Next week: https://github.com/apache/arrow-datafusion/issues/9200
