### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Feb 12, 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9200]
Follow on to [Feb 5, 2024](https://github.com/apache/arrow-datafusion/issues/9121)

**It would be great for other contributors to DataFusion who plan non trivial work could try to make them visible somehow as well** 🙏  (feel free to copy / modify the format)

## My Highlights from Last Week
* Comet (the spark accelerator) completed IP clearance https://github.com/apache/arrow-datafusion-comet/pull/1
* DataFusion SIGMOD paper about DataFusion was [accepted](https://github.com/apache/arrow-datafusion/issues/8373#issuecomment-1925913783)
* We are getting close to beginning the large scale "extract scalar functions from the core" [Organization of functions](https://github.com/apache/arrow-datafusion/issues/9100). Feedback most welcome
* Lots of good new background / docs about what a PruningPredicate is: (thanks @comphead, @jefffrey and @appletreeisyellow  for the reviews and feedback): [example pruning.rs](https://github.com/apache/arrow-datafusion/blob/main/datafusion-examples/examples/pruning.rs) and [docs](https://github.com/apache/arrow-datafusion/blob/dc41ab51a55a35f39f377d16f7d54d96835e8e18/datafusion/core/src/physical_optimizer/pruning.rs#L135)

## Boilerplate Introduction
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

## My (personal) goals for this project
1000 projects are built using DataFusion 📈 

## My (personal) plans for this week
- [ ] get one or two more PRs with more extracted functions https://github.com/apache/arrow-datafusion/issues/9100 and file tickets to track the rest of the work
- [ ] Get PR ready for review to improve ClickBench performance [Faster String Aggregation](https://github.com/apache/arrow-datafusion/issues/7064) (this is my personal fun project and I am so close)
- [ ] More advanced pruning predicates, specifically https://github.com/apache/arrow-datafusion/issues/9171

## Project Queue (list of future projects)
- [ ] SIGMOD paper feedback: #8373 
- [ ] Organize agenda for DataFusion meetup #8522 
- [ ] Improved Statistics: https://github.com/apache/arrow-datafusion/issues/8227 (specifically, https://github.com/apache/arrow-datafusion/issues/8078)

## Projects I plan to help actively help review / plan
- [ ] Improved planning speed https://github.com/apache/arrow-datafusion/issues/5637 with @matthewmturner 
- [ ] Hardening Recursive CTEs https://github.com/apache/arrow-datafusion/issues/462 with @matthewgapp (All that remains is to get memory limiting in place and we could enable this by default). If I don't see motion this week I'll probably file a ticket to track the remaining work explicitly. 

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 
* [Improving performance of aggregation ](https://github.com/apache/arrow-datafusion/issues/7000) - especially high cardinality groupings, where we still lag state of the art by 2x

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/8985
- [ ] https://github.com/apache/arrow-datafusion/pull/9129
- [ ] https://github.com/apache/arrow-datafusion/pull/9181
- [ ] https://github.com/apache/arrow-datafusion/pull/8891
- [ ] https://github.com/apache/arrow-datafusion/pull/9127
- [ ] https://github.com/apache/arrow-datafusion/pull/8566
- [ ] https://github.com/apache/arrow-datafusion/pull/8664
- [ ] https://github.com/apache/arrow-datafusion/pull/8271

Watching
- [ ] https://github.com/apache/arrow-datafusion/pull/8985
- [ ] https://github.com/apache/arrow-datafusion/pull/8891
- [ ] https://github.com/apache/arrow-datafusion/pull/8905

Sqlparser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1122

**Comment by alamb** [comment]
https://github.com/apache/arrow-datafusion/pull/9207

**Comment by alamb** [comment]
Review Queue

DataFusion
- [x] https://github.com/apache/arrow-datafusion/pull/9154#pullrequestreview-1884908701

Sqlparser:
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1122

**Comment by alamb** [comment]
BTW I am on vacation the week of Feb 19,  so I will be reviewing stuff as I can. but likely will not make as much progress as most weeks.

I'll be back the following week as normal
