### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - Feb 26, 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9345]
Follow on to [Feb 12, 2024](https://github.com/apache/arrow-datafusion/issues/9200)

**It would be great for other contributors to DataFusion who plan non trivial work could try to make them visible somehow as well** 🙏  (feel free to copy / modify the format)

## My Highlights from Last Week
* We are beginning beginning the large scale "extract scalar functions from the core" : https://github.com/apache/arrow-datafusion/issues/9285
* merged specialized group values for strings/binary https://github.com/apache/arrow-datafusion/pull/8827

## My (personal) goals for this project
1000 projects are built using DataFusion 📈 

## My (personal) plans for this week
- [x] Catch up on github alerts and reviews from last week
- [x] Revise the proposal for a new top level project and start a vote thread: https://github.com/apache/arrow-datafusion/discussions/6475
- [x] https://github.com/sqlparser-rs/sqlparser-rs/issues/1114
- [x] Organize agenda for DataFusion meetup #8522 

## Project Queue (list of future projects)
- [ ] SIGMOD paper feedback (I plan to work on this the week of March 4, 2024): #8373 
)

## Projects I plan to help actively help review / plan
- [ ] https://github.com/apache/arrow-datafusion/issues/9171 with @appletreeisyellow (we need this for InfluxDB)
- [ ] https://github.com/apache/arrow-datafusion/issues/9285 -- we are starting this work with @jayzhan211  and others
- [ ] Improved planning speed https://github.com/apache/arrow-datafusion/issues/5637 with @matthewmturner 
- [ ] Hardening Recursive CTEs https://github.com/apache/arrow-datafusion/issues/462 with @matthewgapp (All that remains is to get memory limiting in place and we could enable this by default). If I don't see motion this week I'll probably file a ticket to track the remaining work explicitly. 

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 
* [Improving performance of aggregation ](https://github.com/apache/arrow-datafusion/issues/7000) - especially high cardinality groupings, where we still lag state of the art by 2x

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by alamb** [comment]
Review Queue

DataFusion:
- [ ] https://github.com/apache/arrow-datafusion/pull/9307

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9352

SQLParser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1145
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1140
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1144
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1146
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1136
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1135
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1137
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1138
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1141

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9015
- [ ] https://github.com/apache/arrow-datafusion/pull/9304
- [ ] https://github.com/apache/arrow-datafusion/pull/9352
- [ ] https://github.com/apache/arrow-datafusion/pull/9343

SQLParser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1146
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1135
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1137
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1138
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1141

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9304
- [ ] https://github.com/apache/arrow-datafusion/pull/9396
- [ ] https://github.com/apache/arrow-datafusion/pull/9343

SQLParser
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1150
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1151
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1152
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1153
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1154
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1155
- [ ] https://github.com/sqlparser-rs/sqlparser-rs/pull/1156

**Comment by alamb** [comment]
Next week tracked in https://github.com/apache/arrow-datafusion/issues/9453
