### ISSUE TITLE
Table Scan Enhancement Plan

### ISSUE THREAD

**Issue by yjshen** [apache/arrow-datafusion#944]
To make DataFusion scan tables more flexibly and more efficiently, we can take several further steps. (I linked several issues I am aware of)

### Capability: 
- [x] Enable listing/reading remote storage systems in an async way #616 
- [x] Enable file block granularity processing  (row groups or offset range processing instead of currently per-file bases). #1990 
     - [x] #946  
- [x] Enable reading partitioned table. i.e., partition columns value encoded in the file path #133 
- [x] Support table schema evolution. Or in other words, relax the requirement that all files in a table are completely consistent in the schema

### Performance:

- [x] Parallel table file listing #896 
- [x] Scan parquet metadata lazily #871

**Comment by yjshen** [comment]
Also, from my own perspective, I have some extensions to make:
- [ ] Datafusion-hdfs connector
- [ ] Datafusion-hive metastore connector

**Comment by houqp** [comment]
Here is my understanding based on @yjshen 's PRs so far:

* CatalogProvider is a mapping from schema name to SchemaProvider (schema here refers to a collection of tables, not table schema)
* SchemaProvider is a mapping from table name to TableProvider
* TableProvider provides table partitions, field schemas and a scan method to perform table scan using ObjectStore to drive the IO.
    * TableProvider::scan takes push down filter expressions as argument, then issue corresponding ObjectStore list and read calls to perform minimal IO needed to fetch the data from object store

I am guessing a hive metastore connector will need to touch both SchemaProvider and TableProvider? I do think that ObjectStore is too low level to implement hive metastore.

**Comment by yjshen** [comment]
Thanks @houqp for the detailed explanation. After checking delta-rs code as well as what we are doing currently in DataFusion. I have several thoughts:

- It's more natural to have the TableProvider for dealing with filters since it's the abstraction over a table, therefore also a suitable entity for table partition (inferred or user-provided). we could enhance TableProvider with per partition laziness for partition file listing and file metadata extraction.
- `max_partition` shouldn't be related to a Table. It's more reasonable to be deduced or set manually through the planning phase and passed to `ParquetExec` where it actually takes effect.

**Comment by alamb** [comment]
Thanks @yjshen  I plan to review this carefully tomorrow

**Comment by Dandandan** [comment]
@yjshen this seems mostly complete now?

**Comment by alamb** [comment]
I agree this is basically complete, so closing it down. Please feel free to reopen or file a new issue with any remaining work to be done
