### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - March 4, 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9453]
Follow on to [Feb 26, 2024](https://github.com/apache/arrow-datafusion/issues/9345).

Note I am traveling this week and will have limited bandwidth so I will not be as responsive as normal

**It would be great for other contributors to DataFusion who plan non trivial work could try to make them visible somehow as well** 🙏  (feel free to copy / modify the format)

## My Highlights from Last Week
*  The large scale "extract scalar functions from the core" is well under way https://github.com/apache/arrow-datafusion/issues/9285
* Comet blog draft was done https://github.com/apache/arrow-site/pull/479
* Revised the proposal for a new top level project and started a vote thread: https://github.com/apache/arrow-datafusion/discussions/6475
* Agenda for DataFusion meetup 2024 is looking good #8522 
* ScalarUDF::simplify API ready (thanks @jayzhan211!)  https://github.com/apache/arrow-datafusion/pull/9304

## My (personal) goals for this project
1000 projects are built using DataFusion 📈 

## My (personal) plans for this week
- [ ] SIGMOD paper feedback (I plan to work on this the week of March 4, 2024): #8373 )
- [x] Keep up with reviews backlog 🏃 
- [x] File a ticket to track remaing work for Recursive CTEs and close out https://github.com/apache/arrow-datafusion/issues/462 

## Projects I plan to help actively help review / plan
- [ ] https://github.com/apache/arrow-datafusion/issues/9171 with @appletreeisyellow (we need this for InfluxDB)
- [ ] Improved planning speed https://github.com/apache/arrow-datafusion/issues/5637 with @matthewmturner 

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 
* [Improving performance of aggregation ](https://github.com/apache/arrow-datafusion/issues/7000) - especially high cardinality groupings, where we still lag state of the art by 2x

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by alamb** [comment]
I am returning home and will be working through the review backlog 

Current queue:

DataFusion:
- [ ] https://github.com/apache/arrow-datafusion/pull/9482
- [ ] https://github.com/apache/arrow-datafusion/pull/9461

**Comment by alamb** [comment]
DataFusion:
- [ ] https://github.com/apache/arrow-datafusion/pull/9382
- [ ] https://github.com/apache/arrow-datafusion/pull/9469
- [ ] https://github.com/apache/arrow-datafusion/pull/9249

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5481
- [ ] https://github.com/apache/arrow-rs/pull/5485
- [ ] https://github.com/apache/arrow-rs/pull/5486

**Comment by alamb** [comment]
Next week; https://github.com/apache/arrow-datafusion/issues/9555
