### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - March 18, 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9675]
Follow on to https://github.com/apache/arrow-datafusion/issues/9555

**It would be great for other contributors to DataFusion who plan non trivial work could try to make them visible somehow as well** 🙏  (feel free to copy / modify the format)

## My Highlights from Last Week
* https://github.com/apache/arrow-rs/issues/5469 (first step towards https://github.com/apache/arrow-rs/issues/5374 was merged -- thanks @ariesdevil  and @XiangpengHao)
* @backkem  and @devinjdangelo  began implementing https://github.com/apache/arrow-datafusion/issues/8661
* @jayzhan211 started working on improving planning speed with https://github.com/apache/arrow-datafusion/issues/9637 (and found a nice improvement already https://github.com/apache/arrow-datafusion/pull/9657)
* Recursive CTE's enabled by default: https://github.com/apache/arrow-datafusion/pull/9619 (thanks @jonahgao !)
* Large scale "extract scalar functions from the core" continues at good pace way https://github.com/apache/arrow-datafusion/issues/9285 (thanks @jayzhan211  and @erenavsarogullari for being a machine here)

## My (personal) goals for this project
1000 projects are built using DataFusion 📈 

## My (personal) plans for this week
- [x] SIGMOD paper feedback : https://github.com/apache/arrow-datafusion/issues/8373 (10 days left)
- [x] Prepare content for https://github.com/apache/arrow-datafusion/discussions/8522
- [x] Fix https://github.com/apache/arrow-datafusion/issues/9586

## Projects I plan to help actively help review / plan
- [ ] https://github.com/apache/arrow-rs/issues/5374
- [ ] https://github.com/apache/arrow-datafusion/issues/9285
- [x] https://github.com/apache/arrow-datafusion/issues/9171 with @appletreeisyellow (we need this for InfluxDB)
- [ ] https://github.com/apache/arrow-datafusion/issues/9493 with @wiedld 

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 
* [Improving performance of aggregation ](https://github.com/apache/arrow-datafusion/issues/7000) - especially high cardinality groupings, where we still lag state of the art by 2x

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by alamb** [comment]
Reviews:

DataFusion:
- [ ] https://github.com/apache/arrow-datafusion/pull/9613#pullrequestreview-1942546794

**Comment by alamb** [comment]
DataFusion:
- [x] https://github.com/apache/arrow-datafusion/pull/9683#pullrequestreview-1946351083
- [ ] https://github.com/apache/arrow-datafusion/pull/9655
- [ ] https://github.com/apache/arrow-datafusion/pull/9648
- [ ] https://github.com/apache/arrow-datafusion/pull/9593#pullrequestreview-1944059838

Arrow
- [ ] https://github.com/apache/arrow-rs/pull/5500
- [ ] https://github.com/apache/arrow-rs/pull/5531
- [ ] https://github.com/apache/arrow-rs/pull/5525

**Comment by alamb** [comment]
DataFusion
- [x] https://github.com/apache/arrow-datafusion/pull/9595
- [ ]

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9743/files
- [ ] https://github.com/apache/arrow-datafusion/pull/9734
- [ ] https://github.com/apache/arrow-datafusion/pull/9655

**Comment by alamb** [comment]
https://github.com/apache/arrow-datafusion/issues/9796 next week
