### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - March 25, 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9796]
Follow on to https://github.com/apache/arrow-datafusion/issues/9675

**It would be great for other contributors to DataFusion who plan non trivial work could try to make them visible somehow as well** 🙏  (feel free to copy / modify the format)

## My Highlights from Last Week
* We have begin LogicalPlan / Expr --> String translation (https://github.com/apache/arrow-datafusion/issues/9494)
* Large scale "extract scalar functions from the core" continues at good pace way https://github.com/apache/arrow-datafusion/issues/9285 (thanks @jayzhan211  and @erenavsarogullari and @Omega359 for being a machine here)
* Bloom filters are getting better (e.g. https://github.com/apache/arrow-datafusion/pull/9644) -- thanks to @progval 
* We are ready for the 37.0.0 release https://github.com/apache/arrow-datafusion/issues/9682

## My (personal) goals for this project
1000 projects are built using DataFusion 📈 

## My (personal) plans for this week
- [x] Submit SIGMOD final draft feedback : https://github.com/apache/arrow-datafusion/issues/8373 (10 days left)
- [x] Run  https://github.com/apache/arrow-datafusion/discussions/8522
- [x] Make at least one PR for https://github.com/apache/arrow-datafusion/issues/9637

## Projects I plan to help actively help review / plan
- [ ] https://github.com/apache/arrow-rs/issues/5374
- [ ] https://github.com/apache/arrow-datafusion/issues/9285
- [ ] https://github.com/apache/arrow-datafusion/issues/9493 with @wiedld 

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by alamb** [comment]
DataFusion
- [ ] https://github.com/apache/arrow-datafusion/pull/9757
- [ ] https://github.com/apache/arrow-datafusion/pull/9599
- [ ] https://github.com/apache/arrow-datafusion/pull/9655
- [ ] https://github.com/apache/arrow-datafusion/pull/9770

**Comment by MohamedAbdeen21** [comment]
Hey @alamb, on the topic of making datafusion easier to use, can you take a look at #9452 ?  I think everyone has pip and it would be great to have the cli there.

As mentioned, it needs some feedback as I'm not familiar with the release cycle, but it is a good starting point

**Comment by alamb** [comment]
> Hey [@alamb](https://github.com/alamb), on the topic of making datafusion easier to use, can you take a look at [#9452](https://github.com/apache/arrow-datafusion/pull/9452) ? I think everyone has pip and it would be great to have the cli there.

Hi @MohamedAbdeen21  -- thank you I will indeed try and look at this PR later this week. I am sorry I am traveling this week and thus my review bandwidth is very limited. I expect to be back with more bandwidth later in the week

**Comment by alamb** [comment]
Next week: https://github.com/apache/arrow-datafusion/issues/9899
