### ISSUE TITLE
DataFusion weekly project plan (Andrew Lamb) - April 1, 2024

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9899]
Follow on to https://github.com/apache/arrow-datafusion/issues/9796

**It would be great for other contributors to DataFusion who plan non trivial work could try to make them visible somehow as well** 🙏  (feel free to copy / modify the format)

## My Highlights from Last Week
* 37.0.0 release is looking 🚀  https://github.com/apache/arrow-datafusion/issues/9682
* The community made great progress on unparsing expressions: https://github.com/apache/arrow-datafusion/issues/9726
* "extract scalar functions from the core" continues at good pace way https://github.com/apache/arrow-datafusion/issues/9285 (thanks @jayzhan211  and @erenavsarogullari and @Omega359 for keeping the 🚋  running here)
* Submitted SIGMOD final draft : https://github.com/apache/arrow-datafusion/issues/8373
* Ran our first in person meetup (it would be great if others wanted to organize meetups in other geographies): https://github.com/apache/arrow-datafusion/discussions/8522

* We have submitted the proposal for a new top level project for DataFusion to the ASF board: https://github.com/apache/arrow-datafusion/discussions/6475#discussioncomment-8963947

## My (personal) goals 
1000 projects are built using DataFusion 📈 

## My (personal) plans for this week
- [x] Make at least two more PRs for subtasks https://github.com/apache/arrow-datafusion/issues/9637
- [x] Catchup on review backlog
- [x] Writeup ideas on custom / user defined indexes (I mentioned this to @westonpace in person but haven't written it down yet)

## Projects I plan to help actively help review / plan
- [ ] https://github.com/apache/arrow-rs/issues/5374
- [ ] https://github.com/apache/arrow-datafusion/issues/9285
- [ ] https://github.com/apache/arrow-datafusion/issues/9494
- [ ] https://github.com/apache/arrow-datafusion/issues/9493 with @wiedld 

# Algorithm for (my) prioritizing PR reviews
Note there are many [committers](https://arrow.apache.org/committers/) who can and do review and merge PRs, so this is not the priorities of the project as a whole, just the approximate algorithm I use to prioritize my own time

Priority:
1. Bug fixes (where something is just incorrect), especially regressions (where it used to work and now does not)
2. Improvements directly related to features needed for InfluxDB (my employer)
3. Documentation and test improvements (I view these as very strategically important)
4. PRs that I think are strategically important
5. Other new features / additions to functionality (note this is the lowest)

The top strategically important projects in my head are:

* Anything that makes it easier to use DataFusion as a user (docs, examples, better APIs, etc), including [Getting started guide for new users (who want to use DataFusion in their project) ](https://github.com/apache/arrow-datafusion/issues/7014) 
* Anything that improves DataFusion's quality such as bug fixes, and improved / expanded tests, etc
* Making function packages modular and easier to mix/match: https://github.com/apache/arrow-datafusion/issues/8045 

Thus, if you are interested in contributing to DataFusion and are interested in a fast turn around time I would recommend looking into bug fixes / test improvements / documentation or the projects named above

If you propose adding new functionality, the review cycle will likely be longer. You can make it a shorter cycle by looking at the comments on other recent PRs and following the same model (e.g. ensure there are tests in sqllogictest for example, the CI passes, includes documentation, etc)

## Background
The idea of this ticket is make my plans for DataFusion visible, largely for my own personal organizational needs, but also to:
1. Communicate / coordinate in the community 
2. Help provide an interesting summary of what is happening in DataFusion this week

**Comment by seddonm1** [comment]
Sorry for the location and possibly dumb question, but shouldn't all functions be exported here: https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions/src/unicode/mod.rs#L138

I am probably using the library incorrectly but (for example) `LENGTH` will not be registered by the central context here: https://github.com/apache/arrow-datafusion/blob/2f550032140d42d1ee6d8ed86f7790766fa7302e/datafusion/core/src/execution/context/mod.rs#L1450

**Comment by alamb** [comment]
Hi @seddonm1 👋 

> Sorry for the location and possibly dumb question, but shouldn't all functions be exported here: https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions/src/unicode/mod.rs#L138

Yes that is the intention

> 
> I am probably using the library incorrectly but (for example) `LENGTH` will not be registered by the central context here:
> 
> https://github.com/apache/arrow-datafusion/blob/2f550032140d42d1ee6d8ed86f7790766fa7302e/datafusion/core/src/execution/context/mod.rs#L1450

I think `length` is registered as an alias of `character_length`

**Comment by seddonm1** [comment]
Thanks @alamb . If you look at the first link I cannot see anywhere where the `length` alias is actually registered. My queries which previously worked started failing after this update. I haven't investigated if more functions have also not been registered.

**Comment by Omega359** [comment]
aliases for character_length are defined in https://github.com/apache/arrow-datafusion/blob/4bd7c137e0e205140e273a7c25824c94b457c660/datafusion/functions/src/unicode/character_length.rs#L45 and is used during udf registration @ https://github.com/apache/arrow-datafusion/blob/4bd7c137e0e205140e273a7c25824c94b457c660/datafusion/core/src/execution/context/mod.rs#L2137

**Comment by alamb** [comment]
Arrow:
- [ ] https://github.com/apache/arrow-rs/pull/5576

DataFusion
- [x] https://github.com/apache/arrow-datafusion/pull/9926#pullrequestreview-1980090527
- [ ] https://github.com/apache/arrow-datafusion/pull/9813
- [ ] https://github.com/apache/arrow-datafusion/pull/9732
- [ ] https://github.com/apache/arrow-datafusion/pull/9655

**Comment by alamb** [comment]
DataFusion 37.0.0 is released: https://github.com/apache/arrow-datafusion/issues/9682 🌮

**Comment by seddonm1** [comment]
Thanks @Omega359 . I was thrown as the aliases are not registered here https://github.com/apache/arrow-datafusion/blob/3ae029988754c3fd3eb000abd4b76e643b9cbc7b/datafusion/execution/src/registry.rs#L174

**Comment by alamb** [comment]
BTW something cool for next week -- @milenkovicm WASM UDFs https://github.com/apache/arrow-datafusion/issues/9326 / https://github.com/apache/arrow-datafusion/issues/9326#issuecomment-2037743422 / https://github.com/milenkovicm/wasaffi

**Comment by alamb** [comment]
> Really interested to see your thoughts on custom indices, its something were currently working on to improve performance of listing table.

In case anyone else is following along, here are some items related to indexing:
* https://github.com/apache/arrow-datafusion/discussions/9963
* https://github.com/apache/arrow-datafusion/issues/9929

While I had this on the brain, @matthewmturner  I also filed https://github.com/apache/arrow-datafusion/issues/9964 as I suspect others will be interested in helping make ListingTable faster too

**Comment by alamb** [comment]
Reviews:
@jayzhan211  is starting to pull aggregate functions out of the core: https://github.com/apache/arrow-datafusion/pull/9960

**Comment by alamb** [comment]
Next week https://github.com/apache/arrow-datafusion/issues/10002
